/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AchievementRelease implements Serializable {

    private static final long serialVersionUID = -1725986079;

    private String    achievementReleaseId;
    private String    title;
    private Integer   departmentId;
    private Timestamp releaseTime;
    private String    releaseUsername;
    private String    releasePublisher;

    public AchievementRelease() {}

    public AchievementRelease(AchievementRelease value) {
        this.achievementReleaseId = value.achievementReleaseId;
        this.title = value.title;
        this.departmentId = value.departmentId;
        this.releaseTime = value.releaseTime;
        this.releaseUsername = value.releaseUsername;
        this.releasePublisher = value.releasePublisher;
    }

    public AchievementRelease(
        String    achievementReleaseId,
        String    title,
        Integer   departmentId,
        Timestamp releaseTime,
        String    releaseUsername,
        String    releasePublisher
    ) {
        this.achievementReleaseId = achievementReleaseId;
        this.title = title;
        this.departmentId = departmentId;
        this.releaseTime = releaseTime;
        this.releaseUsername = releaseUsername;
        this.releasePublisher = releasePublisher;
    }

    @NotNull
    @Size(max = 64)
    public String getAchievementReleaseId() {
        return this.achievementReleaseId;
    }

    public void setAchievementReleaseId(String achievementReleaseId) {
        this.achievementReleaseId = achievementReleaseId;
    }

    @NotNull
    @Size(max = 200)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @NotNull
    public Integer getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    @NotNull
    public Timestamp getReleaseTime() {
        return this.releaseTime;
    }

    public void setReleaseTime(Timestamp releaseTime) {
        this.releaseTime = releaseTime;
    }

    @NotNull
    @Size(max = 64)
    public String getReleaseUsername() {
        return this.releaseUsername;
    }

    public void setReleaseUsername(String releaseUsername) {
        this.releaseUsername = releaseUsername;
    }

    @NotNull
    @Size(max = 30)
    public String getReleasePublisher() {
        return this.releasePublisher;
    }

    public void setReleasePublisher(String releasePublisher) {
        this.releasePublisher = releasePublisher;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AchievementRelease (");

        sb.append(achievementReleaseId);
        sb.append(", ").append(title);
        sb.append(", ").append(departmentId);
        sb.append(", ").append(releaseTime);
        sb.append(", ").append(releaseUsername);
        sb.append(", ").append(releasePublisher);

        sb.append(")");
        return sb.toString();
    }
}
