/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables.pojos;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AnswerBank implements Serializable {

    private static final long serialVersionUID = 1209423516;

    private String answerBankId;
    private String bankName;
    private String username;
    private Timestamp createDate;

    public AnswerBank() {
    }

    public AnswerBank(AnswerBank value) {
        this.answerBankId = value.answerBankId;
        this.bankName = value.bankName;
        this.username = value.username;
        this.createDate = value.createDate;
    }

    public AnswerBank(
            String answerBankId,
            String bankName,
            String username,
            Timestamp createDate
    ) {
        this.answerBankId = answerBankId;
        this.bankName = bankName;
        this.username = username;
        this.createDate = createDate;
    }

    @NotNull
    @Size(max = 64)
    public String getAnswerBankId() {
        return this.answerBankId;
    }

    public void setAnswerBankId(String answerBankId) {
        this.answerBankId = answerBankId;
    }

    @NotNull
    @Size(max = 100)
    public String getBankName() {
        return this.bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    @NotNull
    @Size(max = 64)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @NotNull
    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AnswerBank (");

        sb.append(answerBankId);
        sb.append(", ").append(bankName);
        sb.append(", ").append(username);
        sb.append(", ").append(createDate);

        sb.append(")");
        return sb.toString();
    }
}
