/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables.pojos;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AnswerSolving implements Serializable {

    private static final long serialVersionUID = 1917946923;

    private String answerSolvingId;
    private String answerSubjectId;
    private String selectKey;
    private String rightKey;
    private String userId;
    private String userName;
    private String answerReleaseId;

    public AnswerSolving() {
    }

    public AnswerSolving(AnswerSolving value) {
        this.answerSolvingId = value.answerSolvingId;
        this.answerSubjectId = value.answerSubjectId;
        this.selectKey = value.selectKey;
        this.rightKey = value.rightKey;
        this.userId = value.userId;
        this.userName = value.userName;
        this.answerReleaseId = value.answerReleaseId;
    }

    public AnswerSolving(
            String answerSolvingId,
            String answerSubjectId,
            String selectKey,
            String rightKey,
            String userId,
            String userName,
            String answerReleaseId
    ) {
        this.answerSolvingId = answerSolvingId;
        this.answerSubjectId = answerSubjectId;
        this.selectKey = selectKey;
        this.rightKey = rightKey;
        this.userId = userId;
        this.userName = userName;
        this.answerReleaseId = answerReleaseId;
    }

    @NotNull
    @Size(max = 64)
    public String getAnswerSolvingId() {
        return this.answerSolvingId;
    }

    public void setAnswerSolvingId(String answerSolvingId) {
        this.answerSolvingId = answerSolvingId;
    }

    @NotNull
    @Size(max = 64)
    public String getAnswerSubjectId() {
        return this.answerSubjectId;
    }

    public void setAnswerSubjectId(String answerSubjectId) {
        this.answerSubjectId = answerSubjectId;
    }

    @Size(max = 10)
    public String getSelectKey() {
        return this.selectKey;
    }

    public void setSelectKey(String selectKey) {
        this.selectKey = selectKey;
    }

    @NotNull
    @Size(max = 10)
    public String getRightKey() {
        return this.rightKey;
    }

    public void setRightKey(String rightKey) {
        this.rightKey = rightKey;
    }

    @NotNull
    @Size(max = 64)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Size(max = 20)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @NotNull
    @Size(max = 64)
    public String getAnswerReleaseId() {
        return this.answerReleaseId;
    }

    public void setAnswerReleaseId(String answerReleaseId) {
        this.answerReleaseId = answerReleaseId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AnswerSolving (");

        sb.append(answerSolvingId);
        sb.append(", ").append(answerSubjectId);
        sb.append(", ").append(selectKey);
        sb.append(", ").append(rightKey);
        sb.append(", ").append(userId);
        sb.append(", ").append(userName);
        sb.append(", ").append(answerReleaseId);

        sb.append(")");
        return sb.toString();
    }
}
