/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EpidemicRegisterData implements Serializable {

    private static final long serialVersionUID = 2091890206;

    private String    epidemicRegisterDataId;
    private String    location;
    private String    address;
    private String    epidemicStatus;
    private String    registerRealName;
    private String    registerType;
    private String    institute;
    private Timestamp registerDate;
    private String    epidemicRegisterReleaseId;
    private String    registerUsername;
    private Integer   channelId;
    private String    remark;

    public EpidemicRegisterData() {}

    public EpidemicRegisterData(EpidemicRegisterData value) {
        this.epidemicRegisterDataId = value.epidemicRegisterDataId;
        this.location = value.location;
        this.address = value.address;
        this.epidemicStatus = value.epidemicStatus;
        this.registerRealName = value.registerRealName;
        this.registerType = value.registerType;
        this.institute = value.institute;
        this.registerDate = value.registerDate;
        this.epidemicRegisterReleaseId = value.epidemicRegisterReleaseId;
        this.registerUsername = value.registerUsername;
        this.channelId = value.channelId;
        this.remark = value.remark;
    }

    public EpidemicRegisterData(
        String    epidemicRegisterDataId,
        String    location,
        String    address,
        String    epidemicStatus,
        String    registerRealName,
        String    registerType,
        String    institute,
        Timestamp registerDate,
        String    epidemicRegisterReleaseId,
        String    registerUsername,
        Integer   channelId,
        String    remark
    ) {
        this.epidemicRegisterDataId = epidemicRegisterDataId;
        this.location = location;
        this.address = address;
        this.epidemicStatus = epidemicStatus;
        this.registerRealName = registerRealName;
        this.registerType = registerType;
        this.institute = institute;
        this.registerDate = registerDate;
        this.epidemicRegisterReleaseId = epidemicRegisterReleaseId;
        this.registerUsername = registerUsername;
        this.channelId = channelId;
        this.remark = remark;
    }

    @NotNull
    @Size(max = 64)
    public String getEpidemicRegisterDataId() {
        return this.epidemicRegisterDataId;
    }

    public void setEpidemicRegisterDataId(String epidemicRegisterDataId) {
        this.epidemicRegisterDataId = epidemicRegisterDataId;
    }

    @Size(max = 200)
    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @Size(max = 300)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @NotNull
    @Size(max = 500)
    public String getEpidemicStatus() {
        return this.epidemicStatus;
    }

    public void setEpidemicStatus(String epidemicStatus) {
        this.epidemicStatus = epidemicStatus;
    }

    @NotNull
    @Size(max = 30)
    public String getRegisterRealName() {
        return this.registerRealName;
    }

    public void setRegisterRealName(String registerRealName) {
        this.registerRealName = registerRealName;
    }

    @NotNull
    @Size(max = 50)
    public String getRegisterType() {
        return this.registerType;
    }

    public void setRegisterType(String registerType) {
        this.registerType = registerType;
    }

    @NotNull
    @Size(max = 500)
    public String getInstitute() {
        return this.institute;
    }

    public void setInstitute(String institute) {
        this.institute = institute;
    }

    @NotNull
    public Timestamp getRegisterDate() {
        return this.registerDate;
    }

    public void setRegisterDate(Timestamp registerDate) {
        this.registerDate = registerDate;
    }

    @NotNull
    @Size(max = 64)
    public String getEpidemicRegisterReleaseId() {
        return this.epidemicRegisterReleaseId;
    }

    public void setEpidemicRegisterReleaseId(String epidemicRegisterReleaseId) {
        this.epidemicRegisterReleaseId = epidemicRegisterReleaseId;
    }

    @NotNull
    @Size(max = 64)
    public String getRegisterUsername() {
        return this.registerUsername;
    }

    public void setRegisterUsername(String registerUsername) {
        this.registerUsername = registerUsername;
    }

    @NotNull
    public Integer getChannelId() {
        return this.channelId;
    }

    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    @Size(max = 200)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EpidemicRegisterData (");

        sb.append(epidemicRegisterDataId);
        sb.append(", ").append(location);
        sb.append(", ").append(address);
        sb.append(", ").append(epidemicStatus);
        sb.append(", ").append(registerRealName);
        sb.append(", ").append(registerType);
        sb.append(", ").append(institute);
        sb.append(", ").append(registerDate);
        sb.append(", ").append(epidemicRegisterReleaseId);
        sb.append(", ").append(registerUsername);
        sb.append(", ").append(channelId);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }
}
