/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables.pojos;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class InternshipReviewAuthorize implements Serializable {

    private static final long serialVersionUID = 684356704;

    private String internshipReleaseId;
    private String username;

    public InternshipReviewAuthorize() {
    }

    public InternshipReviewAuthorize(InternshipReviewAuthorize value) {
        this.internshipReleaseId = value.internshipReleaseId;
        this.username = value.username;
    }

    public InternshipReviewAuthorize(
            String internshipReleaseId,
            String username
    ) {
        this.internshipReleaseId = internshipReleaseId;
        this.username = username;
    }

    @NotNull
    @Size(max = 64)
    public String getInternshipReleaseId() {
        return this.internshipReleaseId;
    }

    public void setInternshipReleaseId(String internshipReleaseId) {
        this.internshipReleaseId = internshipReleaseId;
    }

    @NotNull
    @Size(max = 64)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InternshipReviewAuthorize (");

        sb.append(internshipReleaseId);
        sb.append(", ").append(username);

        sb.append(")");
        return sb.toString();
    }
}
