/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeaverRegisterData implements Serializable {

    private static final long serialVersionUID = -662751002;

    private String    leaverRegisterDataId;
    private Integer   studentId;
    private String    leaverRegisterReleaseId;
    private String    leaverAddress;
    private Timestamp registerDate;
    private String    remark;

    public LeaverRegisterData() {}

    public LeaverRegisterData(LeaverRegisterData value) {
        this.leaverRegisterDataId = value.leaverRegisterDataId;
        this.studentId = value.studentId;
        this.leaverRegisterReleaseId = value.leaverRegisterReleaseId;
        this.leaverAddress = value.leaverAddress;
        this.registerDate = value.registerDate;
        this.remark = value.remark;
    }

    public LeaverRegisterData(
        String    leaverRegisterDataId,
        Integer   studentId,
        String    leaverRegisterReleaseId,
        String    leaverAddress,
        Timestamp registerDate,
        String    remark
    ) {
        this.leaverRegisterDataId = leaverRegisterDataId;
        this.studentId = studentId;
        this.leaverRegisterReleaseId = leaverRegisterReleaseId;
        this.leaverAddress = leaverAddress;
        this.registerDate = registerDate;
        this.remark = remark;
    }

    @NotNull
    @Size(max = 64)
    public String getLeaverRegisterDataId() {
        return this.leaverRegisterDataId;
    }

    public void setLeaverRegisterDataId(String leaverRegisterDataId) {
        this.leaverRegisterDataId = leaverRegisterDataId;
    }

    @NotNull
    public Integer getStudentId() {
        return this.studentId;
    }

    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    @NotNull
    @Size(max = 64)
    public String getLeaverRegisterReleaseId() {
        return this.leaverRegisterReleaseId;
    }

    public void setLeaverRegisterReleaseId(String leaverRegisterReleaseId) {
        this.leaverRegisterReleaseId = leaverRegisterReleaseId;
    }

    @NotNull
    @Size(max = 300)
    public String getLeaverAddress() {
        return this.leaverAddress;
    }

    public void setLeaverAddress(String leaverAddress) {
        this.leaverAddress = leaverAddress;
    }

    @NotNull
    public Timestamp getRegisterDate() {
        return this.registerDate;
    }

    public void setRegisterDate(Timestamp registerDate) {
        this.registerDate = registerDate;
    }

    @Size(max = 200)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LeaverRegisterData (");

        sb.append(leaverRegisterDataId);
        sb.append(", ").append(studentId);
        sb.append(", ").append(leaverRegisterReleaseId);
        sb.append(", ").append(leaverAddress);
        sb.append(", ").append(registerDate);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }
}
