/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables.pojos;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Organize implements Serializable {

    private static final long serialVersionUID = -1180888682;

    private Integer organizeId;
    private String organizeName;
    private Byte organizeIsDel;
    private Integer gradeId;
    private Integer staffId;

    public Organize() {
    }

    public Organize(Organize value) {
        this.organizeId = value.organizeId;
        this.organizeName = value.organizeName;
        this.organizeIsDel = value.organizeIsDel;
        this.gradeId = value.gradeId;
        this.staffId = value.staffId;
    }

    public Organize(
            Integer organizeId,
            String organizeName,
            Byte organizeIsDel,
            Integer gradeId,
            Integer staffId
    ) {
        this.organizeId = organizeId;
        this.organizeName = organizeName;
        this.organizeIsDel = organizeIsDel;
        this.gradeId = gradeId;
        this.staffId = staffId;
    }

    public Integer getOrganizeId() {
        return this.organizeId;
    }

    public void setOrganizeId(Integer organizeId) {
        this.organizeId = organizeId;
    }

    @NotNull
    @Size(max = 200)
    public String getOrganizeName() {
        return this.organizeName;
    }

    public void setOrganizeName(String organizeName) {
        this.organizeName = organizeName;
    }

    public Byte getOrganizeIsDel() {
        return this.organizeIsDel;
    }

    public void setOrganizeIsDel(Byte organizeIsDel) {
        this.organizeIsDel = organizeIsDel;
    }

    @NotNull
    public Integer getGradeId() {
        return this.gradeId;
    }

    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    public Integer getStaffId() {
        return this.staffId;
    }

    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Organize (");

        sb.append(organizeId);
        sb.append(", ").append(organizeName);
        sb.append(", ").append(organizeIsDel);
        sb.append(", ").append(gradeId);
        sb.append(", ").append(staffId);

        sb.append(")");
        return sb.toString();
    }
}
