/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables.pojos;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TrainingSpecialDocumentContent implements Serializable {

    private static final long serialVersionUID = 1823023457;

    private String trainingSpecialDocumentId;
    private String content;

    public TrainingSpecialDocumentContent() {
    }

    public TrainingSpecialDocumentContent(TrainingSpecialDocumentContent value) {
        this.trainingSpecialDocumentId = value.trainingSpecialDocumentId;
        this.content = value.content;
    }

    public TrainingSpecialDocumentContent(
            String trainingSpecialDocumentId,
            String content
    ) {
        this.trainingSpecialDocumentId = trainingSpecialDocumentId;
        this.content = content;
    }

    @NotNull
    @Size(max = 64)
    public String getTrainingSpecialDocumentId() {
        return this.trainingSpecialDocumentId;
    }

    public void setTrainingSpecialDocumentId(String trainingSpecialDocumentId) {
        this.trainingSpecialDocumentId = trainingSpecialDocumentId;
    }

    @NotNull
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TrainingSpecialDocumentContent (");

        sb.append(trainingSpecialDocumentId);
        sb.append(", ").append(content);

        sb.append(")");
        return sb.toString();
    }
}
