/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.zone.domain.tables.AchievementRelease;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AchievementReleaseRecord extends UpdatableRecordImpl<AchievementReleaseRecord> implements Record6<String, String, Integer, Timestamp, String, String> {

    private static final long serialVersionUID = -473669767;

    /**
     * Setter for <code>zhe.achievement_release.achievement_release_id</code>.
     */
    public void setAchievementReleaseId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>zhe.achievement_release.achievement_release_id</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getAchievementReleaseId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>zhe.achievement_release.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>zhe.achievement_release.title</code>.
     */
    @NotNull
    @Size(max = 200)
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>zhe.achievement_release.department_id</code>.
     */
    public void setDepartmentId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>zhe.achievement_release.department_id</code>.
     */
    @NotNull
    public Integer getDepartmentId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>zhe.achievement_release.release_time</code>.
     */
    public void setReleaseTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>zhe.achievement_release.release_time</code>.
     */
    @NotNull
    public Timestamp getReleaseTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>zhe.achievement_release.release_username</code>.
     */
    public void setReleaseUsername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>zhe.achievement_release.release_username</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getReleaseUsername() {
        return (String) get(4);
    }

    /**
     * Setter for <code>zhe.achievement_release.release_publisher</code>.
     */
    public void setReleasePublisher(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>zhe.achievement_release.release_publisher</code>.
     */
    @NotNull
    @Size(max = 30)
    public String getReleasePublisher() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Integer, Timestamp, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Integer, Timestamp, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return AchievementRelease.ACHIEVEMENT_RELEASE.ACHIEVEMENT_RELEASE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AchievementRelease.ACHIEVEMENT_RELEASE.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return AchievementRelease.ACHIEVEMENT_RELEASE.DEPARTMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return AchievementRelease.ACHIEVEMENT_RELEASE.RELEASE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return AchievementRelease.ACHIEVEMENT_RELEASE.RELEASE_USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return AchievementRelease.ACHIEVEMENT_RELEASE.RELEASE_PUBLISHER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getAchievementReleaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDepartmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getReleaseTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getReleaseUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getReleasePublisher();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getAchievementReleaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDepartmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getReleaseTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getReleaseUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getReleasePublisher();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AchievementReleaseRecord value1(String value) {
        setAchievementReleaseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AchievementReleaseRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AchievementReleaseRecord value3(Integer value) {
        setDepartmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AchievementReleaseRecord value4(Timestamp value) {
        setReleaseTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AchievementReleaseRecord value5(String value) {
        setReleaseUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AchievementReleaseRecord value6(String value) {
        setReleasePublisher(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AchievementReleaseRecord values(String value1, String value2, Integer value3, Timestamp value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AchievementReleaseRecord
     */
    public AchievementReleaseRecord() {
        super(AchievementRelease.ACHIEVEMENT_RELEASE);
    }

    /**
     * Create a detached, initialised AchievementReleaseRecord
     */
    public AchievementReleaseRecord(String achievementReleaseId, String title, Integer departmentId, Timestamp releaseTime, String releaseUsername, String releasePublisher) {
        super(AchievementRelease.ACHIEVEMENT_RELEASE);

        set(0, achievementReleaseId);
        set(1, title);
        set(2, departmentId);
        set(3, releaseTime);
        set(4, releaseUsername);
        set(5, releasePublisher);
    }
}
