/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.zone.domain.tables.TrainingAttendAuthorities;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrainingAttendAuthoritiesRecord extends UpdatableRecordImpl<TrainingAttendAuthoritiesRecord> implements Record6<String, String, String, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = -192953709;

    /**
     * Setter for <code>zone.training_attend_authorities.authorities_id</code>.
     */
    public void setAuthoritiesId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>zone.training_attend_authorities.authorities_id</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getAuthoritiesId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>zone.training_attend_authorities.training_attend_id</code>.
     */
    public void setTrainingAttendId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>zone.training_attend_authorities.training_attend_id</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getTrainingAttendId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>zone.training_attend_authorities.username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>zone.training_attend_authorities.username</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>zone.training_attend_authorities.operate_type</code>.
     */
    public void setOperateType(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>zone.training_attend_authorities.operate_type</code>.
     */
    @NotNull
    public Byte getOperateType() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>zone.training_attend_authorities.valid_date</code>.
     */
    public void setValidDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>zone.training_attend_authorities.valid_date</code>.
     */
    @NotNull
    public Timestamp getValidDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>zone.training_attend_authorities.expire_date</code>.
     */
    public void setExpireDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>zone.training_attend_authorities.expire_date</code>.
     */
    @NotNull
    public Timestamp getExpireDate() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, String, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TrainingAttendAuthorities.TRAINING_ATTEND_AUTHORITIES.AUTHORITIES_ID;
    }

    @Override
    public Field<String> field2() {
        return TrainingAttendAuthorities.TRAINING_ATTEND_AUTHORITIES.TRAINING_ATTEND_ID;
    }

    @Override
    public Field<String> field3() {
        return TrainingAttendAuthorities.TRAINING_ATTEND_AUTHORITIES.USERNAME;
    }

    @Override
    public Field<Byte> field4() {
        return TrainingAttendAuthorities.TRAINING_ATTEND_AUTHORITIES.OPERATE_TYPE;
    }

    @Override
    public Field<Timestamp> field5() {
        return TrainingAttendAuthorities.TRAINING_ATTEND_AUTHORITIES.VALID_DATE;
    }

    @Override
    public Field<Timestamp> field6() {
        return TrainingAttendAuthorities.TRAINING_ATTEND_AUTHORITIES.EXPIRE_DATE;
    }

    @Override
    public String component1() {
        return getAuthoritiesId();
    }

    @Override
    public String component2() {
        return getTrainingAttendId();
    }

    @Override
    public String component3() {
        return getUsername();
    }

    @Override
    public Byte component4() {
        return getOperateType();
    }

    @Override
    public Timestamp component5() {
        return getValidDate();
    }

    @Override
    public Timestamp component6() {
        return getExpireDate();
    }

    @Override
    public String value1() {
        return getAuthoritiesId();
    }

    @Override
    public String value2() {
        return getTrainingAttendId();
    }

    @Override
    public String value3() {
        return getUsername();
    }

    @Override
    public Byte value4() {
        return getOperateType();
    }

    @Override
    public Timestamp value5() {
        return getValidDate();
    }

    @Override
    public Timestamp value6() {
        return getExpireDate();
    }

    @Override
    public TrainingAttendAuthoritiesRecord value1(String value) {
        setAuthoritiesId(value);
        return this;
    }

    @Override
    public TrainingAttendAuthoritiesRecord value2(String value) {
        setTrainingAttendId(value);
        return this;
    }

    @Override
    public TrainingAttendAuthoritiesRecord value3(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public TrainingAttendAuthoritiesRecord value4(Byte value) {
        setOperateType(value);
        return this;
    }

    @Override
    public TrainingAttendAuthoritiesRecord value5(Timestamp value) {
        setValidDate(value);
        return this;
    }

    @Override
    public TrainingAttendAuthoritiesRecord value6(Timestamp value) {
        setExpireDate(value);
        return this;
    }

    @Override
    public TrainingAttendAuthoritiesRecord values(String value1, String value2, String value3, Byte value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrainingAttendAuthoritiesRecord
     */
    public TrainingAttendAuthoritiesRecord() {
        super(TrainingAttendAuthorities.TRAINING_ATTEND_AUTHORITIES);
    }

    /**
     * Create a detached, initialised TrainingAttendAuthoritiesRecord
     */
    public TrainingAttendAuthoritiesRecord(String authoritiesId, String trainingAttendId, String username, Byte operateType, Timestamp validDate, Timestamp expireDate) {
        super(TrainingAttendAuthorities.TRAINING_ATTEND_AUTHORITIES);

        set(0, authoritiesId);
        set(1, trainingAttendId);
        set(2, username);
        set(3, operateType);
        set(4, validDate);
        set(5, expireDate);
    }
}
