/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;

import top.zbeboy.zone.domain.tables.TrainingSpecialFile;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrainingSpecialFileRecord extends TableRecordImpl<TrainingSpecialFileRecord> implements Record6<String, String, String, String, Timestamp, Integer> {

    private static final long serialVersionUID = 1485999516;

    /**
     * Setter for <code>zone.training_special_file.file_type_id</code>.
     */
    public void setFileTypeId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>zone.training_special_file.file_type_id</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getFileTypeId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>zone.training_special_file.file_id</code>.
     */
    public void setFileId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>zone.training_special_file.file_id</code>.
     */
    @Size(max = 64)
    public String getFileId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>zone.training_special_file.username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>zone.training_special_file.username</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>zone.training_special_file.uploader</code>.
     */
    public void setUploader(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>zone.training_special_file.uploader</code>.
     */
    @NotNull
    @Size(max = 30)
    public String getUploader() {
        return (String) get(3);
    }

    /**
     * Setter for <code>zone.training_special_file.create_date</code>.
     */
    public void setCreateDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>zone.training_special_file.create_date</code>.
     */
    @NotNull
    public Timestamp getCreateDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>zone.training_special_file.downloads</code>.
     */
    public void setDownloads(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>zone.training_special_file.downloads</code>.
     */
    public Integer getDownloads() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, String, Timestamp, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, String, String, Timestamp, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TrainingSpecialFile.TRAINING_SPECIAL_FILE.FILE_TYPE_ID;
    }

    @Override
    public Field<String> field2() {
        return TrainingSpecialFile.TRAINING_SPECIAL_FILE.FILE_ID;
    }

    @Override
    public Field<String> field3() {
        return TrainingSpecialFile.TRAINING_SPECIAL_FILE.USERNAME;
    }

    @Override
    public Field<String> field4() {
        return TrainingSpecialFile.TRAINING_SPECIAL_FILE.UPLOADER;
    }

    @Override
    public Field<Timestamp> field5() {
        return TrainingSpecialFile.TRAINING_SPECIAL_FILE.CREATE_DATE;
    }

    @Override
    public Field<Integer> field6() {
        return TrainingSpecialFile.TRAINING_SPECIAL_FILE.DOWNLOADS;
    }

    @Override
    public String component1() {
        return getFileTypeId();
    }

    @Override
    public String component2() {
        return getFileId();
    }

    @Override
    public String component3() {
        return getUsername();
    }

    @Override
    public String component4() {
        return getUploader();
    }

    @Override
    public Timestamp component5() {
        return getCreateDate();
    }

    @Override
    public Integer component6() {
        return getDownloads();
    }

    @Override
    public String value1() {
        return getFileTypeId();
    }

    @Override
    public String value2() {
        return getFileId();
    }

    @Override
    public String value3() {
        return getUsername();
    }

    @Override
    public String value4() {
        return getUploader();
    }

    @Override
    public Timestamp value5() {
        return getCreateDate();
    }

    @Override
    public Integer value6() {
        return getDownloads();
    }

    @Override
    public TrainingSpecialFileRecord value1(String value) {
        setFileTypeId(value);
        return this;
    }

    @Override
    public TrainingSpecialFileRecord value2(String value) {
        setFileId(value);
        return this;
    }

    @Override
    public TrainingSpecialFileRecord value3(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public TrainingSpecialFileRecord value4(String value) {
        setUploader(value);
        return this;
    }

    @Override
    public TrainingSpecialFileRecord value5(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public TrainingSpecialFileRecord value6(Integer value) {
        setDownloads(value);
        return this;
    }

    @Override
    public TrainingSpecialFileRecord values(String value1, String value2, String value3, String value4, Timestamp value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrainingSpecialFileRecord
     */
    public TrainingSpecialFileRecord() {
        super(TrainingSpecialFile.TRAINING_SPECIAL_FILE);
    }

    /**
     * Create a detached, initialised TrainingSpecialFileRecord
     */
    public TrainingSpecialFileRecord(String fileTypeId, String fileId, String username, String uploader, Timestamp createDate, Integer downloads) {
        super(TrainingSpecialFile.TRAINING_SPECIAL_FILE);

        set(0, fileTypeId);
        set(1, fileId);
        set(2, username);
        set(3, uploader);
        set(4, createDate);
        set(5, downloads);
    }
}
