/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.zone.domain.tables.TrainingAttendLeaveApply;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrainingAttendLeaveApplyRecord extends UpdatableRecordImpl<TrainingAttendLeaveApplyRecord> implements Record7<String, String, String, Timestamp, String, Byte, String> {

    private static final long serialVersionUID = -1113339363;

    /**
     * Setter for <code>zhe.training_attend_leave_apply.leave_apply_id</code>.
     */
    public void setLeaveApplyId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>zhe.training_attend_leave_apply.leave_apply_id</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getLeaveApplyId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>zhe.training_attend_leave_apply.training_attend_id</code>.
     */
    public void setTrainingAttendId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>zhe.training_attend_leave_apply.training_attend_id</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getTrainingAttendId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>zhe.training_attend_leave_apply.training_users_id</code>.
     */
    public void setTrainingUsersId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>zhe.training_attend_leave_apply.training_users_id</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getTrainingUsersId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>zhe.training_attend_leave_apply.apply_date</code>.
     */
    public void setApplyDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>zhe.training_attend_leave_apply.apply_date</code>.
     */
    @NotNull
    public Timestamp getApplyDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>zhe.training_attend_leave_apply.apply_reason</code>.
     */
    public void setApplyReason(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>zhe.training_attend_leave_apply.apply_reason</code>.
     */
    @NotNull
    @Size(max = 500)
    public String getApplyReason() {
        return (String) get(4);
    }

    /**
     * Setter for <code>zhe.training_attend_leave_apply.apply_state</code>.
     */
    public void setApplyState(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>zhe.training_attend_leave_apply.apply_state</code>.
     */
    @NotNull
    public Byte getApplyState() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>zhe.training_attend_leave_apply.remark</code>.
     */
    public void setRemark(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>zhe.training_attend_leave_apply.remark</code>.
     */
    @Size(max = 500)
    public String getRemark() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, Timestamp, String, Byte, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, Timestamp, String, Byte, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY.LEAVE_APPLY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY.TRAINING_ATTEND_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY.TRAINING_USERS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY.APPLY_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY.APPLY_REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY.APPLY_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getLeaveApplyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTrainingAttendId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTrainingUsersId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getApplyDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getApplyReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getApplyState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getLeaveApplyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTrainingAttendId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTrainingUsersId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getApplyDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getApplyReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getApplyState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainingAttendLeaveApplyRecord value1(String value) {
        setLeaveApplyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainingAttendLeaveApplyRecord value2(String value) {
        setTrainingAttendId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainingAttendLeaveApplyRecord value3(String value) {
        setTrainingUsersId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainingAttendLeaveApplyRecord value4(Timestamp value) {
        setApplyDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainingAttendLeaveApplyRecord value5(String value) {
        setApplyReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainingAttendLeaveApplyRecord value6(Byte value) {
        setApplyState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainingAttendLeaveApplyRecord value7(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainingAttendLeaveApplyRecord values(String value1, String value2, String value3, Timestamp value4, String value5, Byte value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrainingAttendLeaveApplyRecord
     */
    public TrainingAttendLeaveApplyRecord() {
        super(TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY);
    }

    /**
     * Create a detached, initialised TrainingAttendLeaveApplyRecord
     */
    public TrainingAttendLeaveApplyRecord(String leaveApplyId, String trainingAttendId, String trainingUsersId, Timestamp applyDate, String applyReason, Byte applyState, String remark) {
        super(TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY);

        set(0, leaveApplyId);
        set(1, trainingAttendId);
        set(2, trainingUsersId);
        set(3, applyDate);
        set(4, applyReason);
        set(5, applyState);
        set(6, remark);
    }
}
