/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.zone.domain.tables.WeiXinSubscribe;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WeiXinSubscribeRecord extends UpdatableRecordImpl<WeiXinSubscribeRecord> implements Record8<Integer, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -1245567377;

    /**
     * Setter for <code>zone.wei_xin_subscribe.subscribe_id</code>.
     */
    public void setSubscribeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>zone.wei_xin_subscribe.subscribe_id</code>.
     */
    public Integer getSubscribeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>zone.wei_xin_subscribe.template_id</code>.
     */
    public void setTemplateId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>zone.wei_xin_subscribe.template_id</code>.
     */
    @Size(max = 64)
    public String getTemplateId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>zone.wei_xin_subscribe.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>zone.wei_xin_subscribe.type</code>.
     */
    @NotNull
    @Size(max = 10)
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>zone.wei_xin_subscribe.page</code>.
     */
    public void setPage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>zone.wei_xin_subscribe.page</code>.
     */
    @Size(max = 200)
    public String getPage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>zone.wei_xin_subscribe.data</code>.
     */
    public void setData(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>zone.wei_xin_subscribe.data</code>.
     */
    @Size(max = 500)
    public String getData() {
        return (String) get(4);
    }

    /**
     * Setter for <code>zone.wei_xin_subscribe.mini_program_state</code>.
     */
    public void setMiniProgramState(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>zone.wei_xin_subscribe.mini_program_state</code>.
     */
    @Size(max = 20)
    public String getMiniProgramState() {
        return (String) get(5);
    }

    /**
     * Setter for <code>zone.wei_xin_subscribe.lang</code>.
     */
    public void setLang(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>zone.wei_xin_subscribe.lang</code>.
     */
    @Size(max = 10)
    public String getLang() {
        return (String) get(6);
    }

    /**
     * Setter for <code>zone.wei_xin_subscribe.username</code>.
     */
    public void setUsername(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>zone.wei_xin_subscribe.username</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getUsername() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, String, String, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return WeiXinSubscribe.WEI_XIN_SUBSCRIBE.SUBSCRIBE_ID;
    }

    @Override
    public Field<String> field2() {
        return WeiXinSubscribe.WEI_XIN_SUBSCRIBE.TEMPLATE_ID;
    }

    @Override
    public Field<String> field3() {
        return WeiXinSubscribe.WEI_XIN_SUBSCRIBE.TYPE;
    }

    @Override
    public Field<String> field4() {
        return WeiXinSubscribe.WEI_XIN_SUBSCRIBE.PAGE;
    }

    @Override
    public Field<String> field5() {
        return WeiXinSubscribe.WEI_XIN_SUBSCRIBE.DATA;
    }

    @Override
    public Field<String> field6() {
        return WeiXinSubscribe.WEI_XIN_SUBSCRIBE.MINI_PROGRAM_STATE;
    }

    @Override
    public Field<String> field7() {
        return WeiXinSubscribe.WEI_XIN_SUBSCRIBE.LANG;
    }

    @Override
    public Field<String> field8() {
        return WeiXinSubscribe.WEI_XIN_SUBSCRIBE.USERNAME;
    }

    @Override
    public Integer component1() {
        return getSubscribeId();
    }

    @Override
    public String component2() {
        return getTemplateId();
    }

    @Override
    public String component3() {
        return getType();
    }

    @Override
    public String component4() {
        return getPage();
    }

    @Override
    public String component5() {
        return getData();
    }

    @Override
    public String component6() {
        return getMiniProgramState();
    }

    @Override
    public String component7() {
        return getLang();
    }

    @Override
    public String component8() {
        return getUsername();
    }

    @Override
    public Integer value1() {
        return getSubscribeId();
    }

    @Override
    public String value2() {
        return getTemplateId();
    }

    @Override
    public String value3() {
        return getType();
    }

    @Override
    public String value4() {
        return getPage();
    }

    @Override
    public String value5() {
        return getData();
    }

    @Override
    public String value6() {
        return getMiniProgramState();
    }

    @Override
    public String value7() {
        return getLang();
    }

    @Override
    public String value8() {
        return getUsername();
    }

    @Override
    public WeiXinSubscribeRecord value1(Integer value) {
        setSubscribeId(value);
        return this;
    }

    @Override
    public WeiXinSubscribeRecord value2(String value) {
        setTemplateId(value);
        return this;
    }

    @Override
    public WeiXinSubscribeRecord value3(String value) {
        setType(value);
        return this;
    }

    @Override
    public WeiXinSubscribeRecord value4(String value) {
        setPage(value);
        return this;
    }

    @Override
    public WeiXinSubscribeRecord value5(String value) {
        setData(value);
        return this;
    }

    @Override
    public WeiXinSubscribeRecord value6(String value) {
        setMiniProgramState(value);
        return this;
    }

    @Override
    public WeiXinSubscribeRecord value7(String value) {
        setLang(value);
        return this;
    }

    @Override
    public WeiXinSubscribeRecord value8(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public WeiXinSubscribeRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WeiXinSubscribeRecord
     */
    public WeiXinSubscribeRecord() {
        super(WeiXinSubscribe.WEI_XIN_SUBSCRIBE);
    }

    /**
     * Create a detached, initialised WeiXinSubscribeRecord
     */
    public WeiXinSubscribeRecord(Integer subscribeId, String templateId, String type, String page, String data, String miniProgramState, String lang, String username) {
        super(WeiXinSubscribe.WEI_XIN_SUBSCRIBE);

        set(0, subscribeId);
        set(1, templateId);
        set(2, type);
        set(3, page);
        set(4, data);
        set(5, miniProgramState);
        set(6, lang);
        set(7, username);
    }
}
