/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import top.zbeboy.zone.domain.Indexes;
import top.zbeboy.zone.domain.Keys;
import top.zbeboy.zone.domain.Zone;
import top.zbeboy.zone.domain.tables.records.AttendReleaseSubRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttendReleaseSub extends TableImpl<AttendReleaseSubRecord> {

    private static final long serialVersionUID = 1506162097;

    /**
     * The reference instance of <code>zone.attend_release_sub</code>
     */
    public static final AttendReleaseSub ATTEND_RELEASE_SUB = new AttendReleaseSub();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AttendReleaseSubRecord> getRecordType() {
        return AttendReleaseSubRecord.class;
    }

    /**
     * The column <code>zone.attend_release_sub.attend_release_sub_id</code>.
     */
    public final TableField<AttendReleaseSubRecord, Integer> ATTEND_RELEASE_SUB_ID = createField(DSL.name("attend_release_sub_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>zone.attend_release_sub.title</code>.
     */
    public final TableField<AttendReleaseSubRecord, String> TITLE = createField(DSL.name("title"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>zone.attend_release_sub.attend_start_time</code>.
     */
    public final TableField<AttendReleaseSubRecord, Timestamp> ATTEND_START_TIME = createField(DSL.name("attend_start_time"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>zone.attend_release_sub.attend_end_time</code>.
     */
    public final TableField<AttendReleaseSubRecord, Timestamp> ATTEND_END_TIME = createField(DSL.name("attend_end_time"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>zone.attend_release_sub.is_auto</code>.
     */
    public final TableField<AttendReleaseSubRecord, Byte> IS_AUTO = createField(DSL.name("is_auto"), org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>zone.attend_release_sub.valid_date</code>.
     */
    public final TableField<AttendReleaseSubRecord, Timestamp> VALID_DATE = createField(DSL.name("valid_date"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>zone.attend_release_sub.expire_date</code>.
     */
    public final TableField<AttendReleaseSubRecord, Timestamp> EXPIRE_DATE = createField(DSL.name("expire_date"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>zone.attend_release_sub.organize_id</code>.
     */
    public final TableField<AttendReleaseSubRecord, Integer> ORGANIZE_ID = createField(DSL.name("organize_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>zone.attend_release_sub.username</code>.
     */
    public final TableField<AttendReleaseSubRecord, String> USERNAME = createField(DSL.name("username"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>zone.attend_release_sub.attend_release_id</code>.
     */
    public final TableField<AttendReleaseSubRecord, String> ATTEND_RELEASE_ID = createField(DSL.name("attend_release_id"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>zone.attend_release_sub.release_time</code>.
     */
    public final TableField<AttendReleaseSubRecord, Timestamp> RELEASE_TIME = createField(DSL.name("release_time"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>zone.attend_release_sub</code> table reference
     */
    public AttendReleaseSub() {
        this(DSL.name("attend_release_sub"), null);
    }

    /**
     * Create an aliased <code>zone.attend_release_sub</code> table reference
     */
    public AttendReleaseSub(String alias) {
        this(DSL.name(alias), ATTEND_RELEASE_SUB);
    }

    /**
     * Create an aliased <code>zone.attend_release_sub</code> table reference
     */
    public AttendReleaseSub(Name alias) {
        this(alias, ATTEND_RELEASE_SUB);
    }

    private AttendReleaseSub(Name alias, Table<AttendReleaseSubRecord> aliased) {
        this(alias, aliased, null);
    }

    private AttendReleaseSub(Name alias, Table<AttendReleaseSubRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AttendReleaseSub(Table<O> child, ForeignKey<O, AttendReleaseSubRecord> key) {
        super(child, key, ATTEND_RELEASE_SUB);
    }

    @Override
    public Schema getSchema() {
        return Zone.ZONE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ATTEND_RELEASE_SUB_ATTEND_RELEASE_ID, Indexes.ATTEND_RELEASE_SUB_ORGANIZE_ID, Indexes.ATTEND_RELEASE_SUB_PRIMARY, Indexes.ATTEND_RELEASE_SUB_USERNAME);
    }

    @Override
    public Identity<AttendReleaseSubRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ATTEND_RELEASE_SUB;
    }

    @Override
    public UniqueKey<AttendReleaseSubRecord> getPrimaryKey() {
        return Keys.KEY_ATTEND_RELEASE_SUB_PRIMARY;
    }

    @Override
    public List<UniqueKey<AttendReleaseSubRecord>> getKeys() {
        return Arrays.<UniqueKey<AttendReleaseSubRecord>>asList(Keys.KEY_ATTEND_RELEASE_SUB_PRIMARY);
    }

    @Override
    public List<ForeignKey<AttendReleaseSubRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AttendReleaseSubRecord, ?>>asList(Keys.ATTEND_RELEASE_SUB_IBFK_2, Keys.ATTEND_RELEASE_SUB_IBFK_3, Keys.ATTEND_RELEASE_SUB_IBFK_1);
    }

    public Organize organize() {
        return new Organize(this, Keys.ATTEND_RELEASE_SUB_IBFK_2);
    }

    public Users users() {
        return new Users(this, Keys.ATTEND_RELEASE_SUB_IBFK_3);
    }

    public AttendRelease attendRelease() {
        return new AttendRelease(this, Keys.ATTEND_RELEASE_SUB_IBFK_1);
    }

    @Override
    public AttendReleaseSub as(String alias) {
        return new AttendReleaseSub(DSL.name(alias), this);
    }

    @Override
    public AttendReleaseSub as(Name alias) {
        return new AttendReleaseSub(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AttendReleaseSub rename(String name) {
        return new AttendReleaseSub(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AttendReleaseSub rename(Name name) {
        return new AttendReleaseSub(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, String, Timestamp, Timestamp, Byte, Timestamp, Timestamp, Integer, String, String, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
