/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.zbeboy.zone.domain.tables.AnswerRelease;
import top.zbeboy.zone.domain.tables.records.AnswerReleaseRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class AnswerReleaseDao extends DAOImpl<AnswerReleaseRecord, top.zbeboy.zone.domain.tables.pojos.AnswerRelease, String> {

    /**
     * Create a new AnswerReleaseDao without any configuration
     */
    public AnswerReleaseDao() {
        super(AnswerRelease.ANSWER_RELEASE, top.zbeboy.zone.domain.tables.pojos.AnswerRelease.class);
    }

    /**
     * Create a new AnswerReleaseDao with an attached configuration
     */
    @Autowired
    public AnswerReleaseDao(Configuration configuration) {
        super(AnswerRelease.ANSWER_RELEASE, top.zbeboy.zone.domain.tables.pojos.AnswerRelease.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(top.zbeboy.zone.domain.tables.pojos.AnswerRelease object) {
        return object.getAnswerReleaseId();
    }

    /**
     * Fetch records that have <code>answer_release_id IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.AnswerRelease> fetchByAnswerReleaseId(String... values) {
        return fetch(AnswerRelease.ANSWER_RELEASE.ANSWER_RELEASE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>answer_release_id = value</code>
     */
    public top.zbeboy.zone.domain.tables.pojos.AnswerRelease fetchOneByAnswerReleaseId(String value) {
        return fetchOne(AnswerRelease.ANSWER_RELEASE.ANSWER_RELEASE_ID, value);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.AnswerRelease> fetchByTitle(String... values) {
        return fetch(AnswerRelease.ANSWER_RELEASE.TITLE, values);
    }

    /**
     * Fetch records that have <code>start_time IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.AnswerRelease> fetchByStartTime(Timestamp... values) {
        return fetch(AnswerRelease.ANSWER_RELEASE.START_TIME, values);
    }

    /**
     * Fetch records that have <code>end_time IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.AnswerRelease> fetchByEndTime(Timestamp... values) {
        return fetch(AnswerRelease.ANSWER_RELEASE.END_TIME, values);
    }

    /**
     * Fetch records that have <code>answer_bank_id IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.AnswerRelease> fetchByAnswerBankId(String... values) {
        return fetch(AnswerRelease.ANSWER_RELEASE.ANSWER_BANK_ID, values);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.AnswerRelease> fetchByUsername(String... values) {
        return fetch(AnswerRelease.ANSWER_RELEASE.USERNAME, values);
    }

    /**
     * Fetch records that have <code>release_time IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.AnswerRelease> fetchByReleaseTime(Timestamp... values) {
        return fetch(AnswerRelease.ANSWER_RELEASE.RELEASE_TIME, values);
    }
}
