/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables.daos;


import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import top.zbeboy.zone.domain.tables.Application;
import top.zbeboy.zone.domain.tables.records.ApplicationRecord;

import javax.annotation.Generated;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Repository
public class ApplicationDao extends DAOImpl<ApplicationRecord, top.zbeboy.zone.domain.tables.pojos.Application, String> {

    /**
     * Create a new ApplicationDao without any configuration
     */
    public ApplicationDao() {
        super(Application.APPLICATION, top.zbeboy.zone.domain.tables.pojos.Application.class);
    }

    /**
     * Create a new ApplicationDao with an attached configuration
     */
    @Autowired
    public ApplicationDao(Configuration configuration) {
        super(Application.APPLICATION, top.zbeboy.zone.domain.tables.pojos.Application.class, configuration);
    }

    @Override
    public String getId(top.zbeboy.zone.domain.tables.pojos.Application object) {
        return object.getApplicationId();
    }

    /**
     * Fetch records that have <code>application_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.Application> fetchRangeOfApplicationId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Application.APPLICATION.APPLICATION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>application_id IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.Application> fetchByApplicationId(String... values) {
        return fetch(Application.APPLICATION.APPLICATION_ID, values);
    }

    /**
     * Fetch a unique record that has <code>application_id = value</code>
     */
    public top.zbeboy.zone.domain.tables.pojos.Application fetchOneByApplicationId(String value) {
        return fetchOne(Application.APPLICATION.APPLICATION_ID, value);
    }

    /**
     * Fetch records that have <code>application_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.Application> fetchRangeOfApplicationName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Application.APPLICATION.APPLICATION_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>application_name IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.Application> fetchByApplicationName(String... values) {
        return fetch(Application.APPLICATION.APPLICATION_NAME, values);
    }

    /**
     * Fetch records that have <code>application_sort BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.Application> fetchRangeOfApplicationSort(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Application.APPLICATION.APPLICATION_SORT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>application_sort IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.Application> fetchByApplicationSort(Integer... values) {
        return fetch(Application.APPLICATION.APPLICATION_SORT, values);
    }

    /**
     * Fetch records that have <code>application_pid BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.Application> fetchRangeOfApplicationPid(String lowerInclusive, String upperInclusive) {
        return fetchRange(Application.APPLICATION.APPLICATION_PID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>application_pid IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.Application> fetchByApplicationPid(String... values) {
        return fetch(Application.APPLICATION.APPLICATION_PID, values);
    }

    /**
     * Fetch records that have <code>application_url BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.Application> fetchRangeOfApplicationUrl(String lowerInclusive, String upperInclusive) {
        return fetchRange(Application.APPLICATION.APPLICATION_URL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>application_url IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.Application> fetchByApplicationUrl(String... values) {
        return fetch(Application.APPLICATION.APPLICATION_URL, values);
    }

    /**
     * Fetch records that have <code>application_code BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.Application> fetchRangeOfApplicationCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Application.APPLICATION.APPLICATION_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>application_code IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.Application> fetchByApplicationCode(String... values) {
        return fetch(Application.APPLICATION.APPLICATION_CODE, values);
    }

    /**
     * Fetch records that have <code>application_en_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.Application> fetchRangeOfApplicationEnName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Application.APPLICATION.APPLICATION_EN_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>application_en_name IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.Application> fetchByApplicationEnName(String... values) {
        return fetch(Application.APPLICATION.APPLICATION_EN_NAME, values);
    }

    /**
     * Fetch records that have <code>icon BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.Application> fetchRangeOfIcon(String lowerInclusive, String upperInclusive) {
        return fetchRange(Application.APPLICATION.ICON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>icon IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.Application> fetchByIcon(String... values) {
        return fetch(Application.APPLICATION.ICON, values);
    }

    /**
     * Fetch records that have <code>application_data_url_start_with BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.Application> fetchRangeOfApplicationDataUrlStartWith(String lowerInclusive, String upperInclusive) {
        return fetchRange(Application.APPLICATION.APPLICATION_DATA_URL_START_WITH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>application_data_url_start_with IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.Application> fetchByApplicationDataUrlStartWith(String... values) {
        return fetch(Application.APPLICATION.APPLICATION_DATA_URL_START_WITH, values);
    }
}
