/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables.daos;


import java.sql.Time;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record4;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.zbeboy.zone.domain.tables.CurriculumContent;
import top.zbeboy.zone.domain.tables.records.CurriculumContentRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class CurriculumContentDao extends DAOImpl<CurriculumContentRecord, top.zbeboy.zone.domain.tables.pojos.CurriculumContent, Record4<String, String, Byte, Integer>> {

    /**
     * Create a new CurriculumContentDao without any configuration
     */
    public CurriculumContentDao() {
        super(CurriculumContent.CURRICULUM_CONTENT, top.zbeboy.zone.domain.tables.pojos.CurriculumContent.class);
    }

    /**
     * Create a new CurriculumContentDao with an attached configuration
     */
    @Autowired
    public CurriculumContentDao(Configuration configuration) {
        super(CurriculumContent.CURRICULUM_CONTENT, top.zbeboy.zone.domain.tables.pojos.CurriculumContent.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record4<String, String, Byte, Integer> getId(top.zbeboy.zone.domain.tables.pojos.CurriculumContent object) {
        return compositeKeyRecord(object.getCurriculumReleaseId(), object.getSchoolroomName(), object.getWeek(), object.getBatchNum());
    }

    /**
     * Fetch records that have <code>curriculum_release_id IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.CurriculumContent> fetchByCurriculumReleaseId(String... values) {
        return fetch(CurriculumContent.CURRICULUM_CONTENT.CURRICULUM_RELEASE_ID, values);
    }

    /**
     * Fetch records that have <code>schoolroom_name IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.CurriculumContent> fetchBySchoolroomName(String... values) {
        return fetch(CurriculumContent.CURRICULUM_CONTENT.SCHOOLROOM_NAME, values);
    }

    /**
     * Fetch records that have <code>course_name IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.CurriculumContent> fetchByCourseName(String... values) {
        return fetch(CurriculumContent.CURRICULUM_CONTENT.COURSE_NAME, values);
    }

    /**
     * Fetch records that have <code>week IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.CurriculumContent> fetchByWeek(Byte... values) {
        return fetch(CurriculumContent.CURRICULUM_CONTENT.WEEK, values);
    }

    /**
     * Fetch records that have <code>start_week IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.CurriculumContent> fetchByStartWeek(Byte... values) {
        return fetch(CurriculumContent.CURRICULUM_CONTENT.START_WEEK, values);
    }

    /**
     * Fetch records that have <code>end_week IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.CurriculumContent> fetchByEndWeek(Byte... values) {
        return fetch(CurriculumContent.CURRICULUM_CONTENT.END_WEEK, values);
    }

    /**
     * Fetch records that have <code>start_time IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.CurriculumContent> fetchByStartTime(Time... values) {
        return fetch(CurriculumContent.CURRICULUM_CONTENT.START_TIME, values);
    }

    /**
     * Fetch records that have <code>end_time IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.CurriculumContent> fetchByEndTime(Time... values) {
        return fetch(CurriculumContent.CURRICULUM_CONTENT.END_TIME, values);
    }

    /**
     * Fetch records that have <code>staff_name IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.CurriculumContent> fetchByStaffName(String... values) {
        return fetch(CurriculumContent.CURRICULUM_CONTENT.STAFF_NAME, values);
    }

    /**
     * Fetch records that have <code>hours IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.CurriculumContent> fetchByHours(Double... values) {
        return fetch(CurriculumContent.CURRICULUM_CONTENT.HOURS, values);
    }

    /**
     * Fetch records that have <code>organize_name IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.CurriculumContent> fetchByOrganizeName(String... values) {
        return fetch(CurriculumContent.CURRICULUM_CONTENT.ORGANIZE_NAME, values);
    }

    /**
     * Fetch records that have <code>batch_num IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.CurriculumContent> fetchByBatchNum(Integer... values) {
        return fetch(CurriculumContent.CURRICULUM_CONTENT.BATCH_NUM, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.CurriculumContent> fetchByCreateTime(Timestamp... values) {
        return fetch(CurriculumContent.CURRICULUM_CONTENT.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>plan_username IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.CurriculumContent> fetchByPlanUsername(String... values) {
        return fetch(CurriculumContent.CURRICULUM_CONTENT.PLAN_USERNAME, values);
    }

    /**
     * Fetch records that have <code>plan_publisher IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.CurriculumContent> fetchByPlanPublisher(String... values) {
        return fetch(CurriculumContent.CURRICULUM_CONTENT.PLAN_PUBLISHER, values);
    }
}
