/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables.daos;


import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.zbeboy.zone.domain.tables.InternshipCompany;
import top.zbeboy.zone.domain.tables.records.InternshipCompanyRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class InternshipCompanyDao extends DAOImpl<InternshipCompanyRecord, top.zbeboy.zone.domain.tables.pojos.InternshipCompany, String> {

    /**
     * Create a new InternshipCompanyDao without any configuration
     */
    public InternshipCompanyDao() {
        super(InternshipCompany.INTERNSHIP_COMPANY, top.zbeboy.zone.domain.tables.pojos.InternshipCompany.class);
    }

    /**
     * Create a new InternshipCompanyDao with an attached configuration
     */
    @Autowired
    public InternshipCompanyDao(Configuration configuration) {
        super(InternshipCompany.INTERNSHIP_COMPANY, top.zbeboy.zone.domain.tables.pojos.InternshipCompany.class, configuration);
    }

    @Override
    public String getId(top.zbeboy.zone.domain.tables.pojos.InternshipCompany object) {
        return object.getInternshipCompanyId();
    }

    /**
     * Fetch records that have <code>internship_company_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfInternshipCompanyId(String lowerInclusive, String upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.INTERNSHIP_COMPANY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>internship_company_id IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByInternshipCompanyId(String... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.INTERNSHIP_COMPANY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>internship_company_id = value</code>
     */
    public top.zbeboy.zone.domain.tables.pojos.InternshipCompany fetchOneByInternshipCompanyId(String value) {
        return fetchOne(InternshipCompany.INTERNSHIP_COMPANY.INTERNSHIP_COMPANY_ID, value);
    }

    /**
     * Fetch records that have <code>student_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfStudentName(String lowerInclusive, String upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.STUDENT_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>student_name IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByStudentName(String... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.STUDENT_NAME, values);
    }

    /**
     * Fetch records that have <code>college_class BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfCollegeClass(String lowerInclusive, String upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.COLLEGE_CLASS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>college_class IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByCollegeClass(String... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.COLLEGE_CLASS, values);
    }

    /**
     * Fetch records that have <code>student_sex BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfStudentSex(String lowerInclusive, String upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.STUDENT_SEX, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>student_sex IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByStudentSex(String... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.STUDENT_SEX, values);
    }

    /**
     * Fetch records that have <code>student_number BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfStudentNumber(String lowerInclusive, String upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.STUDENT_NUMBER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>student_number IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByStudentNumber(String... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.STUDENT_NUMBER, values);
    }

    /**
     * Fetch records that have <code>phone_number BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfPhoneNumber(String lowerInclusive, String upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.PHONE_NUMBER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>phone_number IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByPhoneNumber(String... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.PHONE_NUMBER, values);
    }

    /**
     * Fetch records that have <code>qq_mailbox BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfQqMailbox(String lowerInclusive, String upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.QQ_MAILBOX, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>qq_mailbox IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByQqMailbox(String... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.QQ_MAILBOX, values);
    }

    /**
     * Fetch records that have <code>parental_contact BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfParentalContact(String lowerInclusive, String upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.PARENTAL_CONTACT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>parental_contact IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByParentalContact(String... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.PARENTAL_CONTACT, values);
    }

    /**
     * Fetch records that have <code>headmaster BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfHeadmaster(String lowerInclusive, String upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.HEADMASTER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>headmaster IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByHeadmaster(String... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.HEADMASTER, values);
    }

    /**
     * Fetch records that have <code>headmaster_contact BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfHeadmasterContact(String lowerInclusive, String upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.HEADMASTER_CONTACT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>headmaster_contact IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByHeadmasterContact(String... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.HEADMASTER_CONTACT, values);
    }

    /**
     * Fetch records that have <code>internship_company_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfInternshipCompanyName(String lowerInclusive, String upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.INTERNSHIP_COMPANY_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>internship_company_name IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByInternshipCompanyName(String... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.INTERNSHIP_COMPANY_NAME, values);
    }

    /**
     * Fetch records that have <code>internship_company_address BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfInternshipCompanyAddress(String lowerInclusive, String upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.INTERNSHIP_COMPANY_ADDRESS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>internship_company_address IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByInternshipCompanyAddress(String... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.INTERNSHIP_COMPANY_ADDRESS, values);
    }

    /**
     * Fetch records that have <code>internship_company_contacts BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfInternshipCompanyContacts(String lowerInclusive, String upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.INTERNSHIP_COMPANY_CONTACTS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>internship_company_contacts IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByInternshipCompanyContacts(String... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.INTERNSHIP_COMPANY_CONTACTS, values);
    }

    /**
     * Fetch records that have <code>internship_company_tel BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfInternshipCompanyTel(String lowerInclusive, String upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.INTERNSHIP_COMPANY_TEL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>internship_company_tel IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByInternshipCompanyTel(String... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.INTERNSHIP_COMPANY_TEL, values);
    }

    /**
     * Fetch records that have <code>school_guidance_teacher BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfSchoolGuidanceTeacher(String lowerInclusive, String upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.SCHOOL_GUIDANCE_TEACHER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>school_guidance_teacher IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchBySchoolGuidanceTeacher(String... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.SCHOOL_GUIDANCE_TEACHER, values);
    }

    /**
     * Fetch records that have <code>school_guidance_teacher_tel BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfSchoolGuidanceTeacherTel(String lowerInclusive, String upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.SCHOOL_GUIDANCE_TEACHER_TEL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>school_guidance_teacher_tel IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchBySchoolGuidanceTeacherTel(String... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.SCHOOL_GUIDANCE_TEACHER_TEL, values);
    }

    /**
     * Fetch records that have <code>start_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfStartTime(Date lowerInclusive, Date upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.START_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>start_time IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByStartTime(Date... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.START_TIME, values);
    }

    /**
     * Fetch records that have <code>end_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfEndTime(Date lowerInclusive, Date upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.END_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>end_time IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByEndTime(Date... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.END_TIME, values);
    }

    /**
     * Fetch records that have <code>commitment_book BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfCommitmentBook(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.COMMITMENT_BOOK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>commitment_book IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByCommitmentBook(Byte... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.COMMITMENT_BOOK, values);
    }

    /**
     * Fetch records that have <code>safety_responsibility_book BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfSafetyResponsibilityBook(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.SAFETY_RESPONSIBILITY_BOOK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>safety_responsibility_book IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchBySafetyResponsibilityBook(Byte... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.SAFETY_RESPONSIBILITY_BOOK, values);
    }

    /**
     * Fetch records that have <code>practice_agreement BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfPracticeAgreement(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.PRACTICE_AGREEMENT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>practice_agreement IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByPracticeAgreement(Byte... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.PRACTICE_AGREEMENT, values);
    }

    /**
     * Fetch records that have <code>internship_application BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfInternshipApplication(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.INTERNSHIP_APPLICATION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>internship_application IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByInternshipApplication(Byte... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.INTERNSHIP_APPLICATION, values);
    }

    /**
     * Fetch records that have <code>practice_receiving BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfPracticeReceiving(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.PRACTICE_RECEIVING, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>practice_receiving IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByPracticeReceiving(Byte... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.PRACTICE_RECEIVING, values);
    }

    /**
     * Fetch records that have <code>security_education_agreement BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfSecurityEducationAgreement(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.SECURITY_EDUCATION_AGREEMENT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>security_education_agreement IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchBySecurityEducationAgreement(Byte... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.SECURITY_EDUCATION_AGREEMENT, values);
    }

    /**
     * Fetch records that have <code>parental_consent BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfParentalConsent(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.PARENTAL_CONSENT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>parental_consent IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByParentalConsent(Byte... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.PARENTAL_CONSENT, values);
    }

    /**
     * Fetch records that have <code>student_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfStudentId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.STUDENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>student_id IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByStudentId(Integer... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.STUDENT_ID, values);
    }

    /**
     * Fetch records that have <code>student_username BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfStudentUsername(String lowerInclusive, String upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.STUDENT_USERNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>student_username IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByStudentUsername(String... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.STUDENT_USERNAME, values);
    }

    /**
     * Fetch records that have <code>internship_release_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchRangeOfInternshipReleaseId(String lowerInclusive, String upperInclusive) {
        return fetchRange(InternshipCompany.INTERNSHIP_COMPANY.INTERNSHIP_RELEASE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>internship_release_id IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.InternshipCompany> fetchByInternshipReleaseId(String... values) {
        return fetch(InternshipCompany.INTERNSHIP_COMPANY.INTERNSHIP_RELEASE_ID, values);
    }
}
