/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.zbeboy.zone.domain.tables.LeaverRegisterOption;
import top.zbeboy.zone.domain.tables.records.LeaverRegisterOptionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class LeaverRegisterOptionDao extends DAOImpl<LeaverRegisterOptionRecord, top.zbeboy.zone.domain.tables.pojos.LeaverRegisterOption, String> {

    /**
     * Create a new LeaverRegisterOptionDao without any configuration
     */
    public LeaverRegisterOptionDao() {
        super(LeaverRegisterOption.LEAVER_REGISTER_OPTION, top.zbeboy.zone.domain.tables.pojos.LeaverRegisterOption.class);
    }

    /**
     * Create a new LeaverRegisterOptionDao with an attached configuration
     */
    @Autowired
    public LeaverRegisterOptionDao(Configuration configuration) {
        super(LeaverRegisterOption.LEAVER_REGISTER_OPTION, top.zbeboy.zone.domain.tables.pojos.LeaverRegisterOption.class, configuration);
    }

    @Override
    public String getId(top.zbeboy.zone.domain.tables.pojos.LeaverRegisterOption object) {
        return object.getLeaverRegisterOptionId();
    }

    /**
     * Fetch records that have <code>leaver_register_option_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.LeaverRegisterOption> fetchRangeOfLeaverRegisterOptionId(String lowerInclusive, String upperInclusive) {
        return fetchRange(LeaverRegisterOption.LEAVER_REGISTER_OPTION.LEAVER_REGISTER_OPTION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>leaver_register_option_id IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.LeaverRegisterOption> fetchByLeaverRegisterOptionId(String... values) {
        return fetch(LeaverRegisterOption.LEAVER_REGISTER_OPTION.LEAVER_REGISTER_OPTION_ID, values);
    }

    /**
     * Fetch a unique record that has <code>leaver_register_option_id = value</code>
     */
    public top.zbeboy.zone.domain.tables.pojos.LeaverRegisterOption fetchOneByLeaverRegisterOptionId(String value) {
        return fetchOne(LeaverRegisterOption.LEAVER_REGISTER_OPTION.LEAVER_REGISTER_OPTION_ID, value);
    }

    /**
     * Fetch records that have <code>leaver_register_release_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.LeaverRegisterOption> fetchRangeOfLeaverRegisterReleaseId(String lowerInclusive, String upperInclusive) {
        return fetchRange(LeaverRegisterOption.LEAVER_REGISTER_OPTION.LEAVER_REGISTER_RELEASE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>leaver_register_release_id IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.LeaverRegisterOption> fetchByLeaverRegisterReleaseId(String... values) {
        return fetch(LeaverRegisterOption.LEAVER_REGISTER_OPTION.LEAVER_REGISTER_RELEASE_ID, values);
    }

    /**
     * Fetch records that have <code>option_content BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.LeaverRegisterOption> fetchRangeOfOptionContent(String lowerInclusive, String upperInclusive) {
        return fetchRange(LeaverRegisterOption.LEAVER_REGISTER_OPTION.OPTION_CONTENT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>option_content IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.LeaverRegisterOption> fetchByOptionContent(String... values) {
        return fetch(LeaverRegisterOption.LEAVER_REGISTER_OPTION.OPTION_CONTENT, values);
    }

    /**
     * Fetch records that have <code>sort BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.LeaverRegisterOption> fetchRangeOfSort(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(LeaverRegisterOption.LEAVER_REGISTER_OPTION.SORT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sort IN (values)</code>
     */
    public List<top.zbeboy.zone.domain.tables.pojos.LeaverRegisterOption> fetchBySort(Byte... values) {
        return fetch(LeaverRegisterOption.LEAVER_REGISTER_OPTION.SORT, values);
    }
}
