/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import top.zbeboy.zone.domain.tables.AcademicTitle;
import top.zbeboy.zone.domain.tables.AchievementRelease;
import top.zbeboy.zone.domain.tables.AchievementSyncData;
import top.zbeboy.zone.domain.tables.AchievementSyncManifest;
import top.zbeboy.zone.domain.tables.AchievementSyncStudent;
import top.zbeboy.zone.domain.tables.Application;
import top.zbeboy.zone.domain.tables.Authorities;
import top.zbeboy.zone.domain.tables.Building;
import top.zbeboy.zone.domain.tables.College;
import top.zbeboy.zone.domain.tables.CollegeApplication;
import top.zbeboy.zone.domain.tables.CollegeRole;
import top.zbeboy.zone.domain.tables.Course;
import top.zbeboy.zone.domain.tables.CurriculumContent;
import top.zbeboy.zone.domain.tables.CurriculumRelease;
import top.zbeboy.zone.domain.tables.Department;
import top.zbeboy.zone.domain.tables.Files;
import top.zbeboy.zone.domain.tables.Grade;
import top.zbeboy.zone.domain.tables.Nation;
import top.zbeboy.zone.domain.tables.Organize;
import top.zbeboy.zone.domain.tables.PoliticalLandscape;
import top.zbeboy.zone.domain.tables.QuestionFeedback;
import top.zbeboy.zone.domain.tables.Role;
import top.zbeboy.zone.domain.tables.RoleApplication;
import top.zbeboy.zone.domain.tables.School;
import top.zbeboy.zone.domain.tables.Schoolroom;
import top.zbeboy.zone.domain.tables.Science;
import top.zbeboy.zone.domain.tables.Staff;
import top.zbeboy.zone.domain.tables.Student;
import top.zbeboy.zone.domain.tables.SystemConfigure;
import top.zbeboy.zone.domain.tables.SystemMailboxLog;
import top.zbeboy.zone.domain.tables.SystemNotify;
import top.zbeboy.zone.domain.tables.SystemOperatorLog;
import top.zbeboy.zone.domain.tables.SystemSmsLog;
import top.zbeboy.zone.domain.tables.TrainingAttend;
import top.zbeboy.zone.domain.tables.TrainingAttendAuthorities;
import top.zbeboy.zone.domain.tables.TrainingAttendLeaveApply;
import top.zbeboy.zone.domain.tables.TrainingAttendUsers;
import top.zbeboy.zone.domain.tables.TrainingLabs;
import top.zbeboy.zone.domain.tables.TrainingRelease;
import top.zbeboy.zone.domain.tables.TrainingUsers;
import top.zbeboy.zone.domain.tables.UserNotify;
import top.zbeboy.zone.domain.tables.Users;
import top.zbeboy.zone.domain.tables.UsersType;
import top.zbeboy.zone.domain.tables.records.AcademicTitleRecord;
import top.zbeboy.zone.domain.tables.records.AchievementReleaseRecord;
import top.zbeboy.zone.domain.tables.records.AchievementSyncDataRecord;
import top.zbeboy.zone.domain.tables.records.AchievementSyncManifestRecord;
import top.zbeboy.zone.domain.tables.records.AchievementSyncStudentRecord;
import top.zbeboy.zone.domain.tables.records.ApplicationRecord;
import top.zbeboy.zone.domain.tables.records.AuthoritiesRecord;
import top.zbeboy.zone.domain.tables.records.BuildingRecord;
import top.zbeboy.zone.domain.tables.records.CollegeApplicationRecord;
import top.zbeboy.zone.domain.tables.records.CollegeRecord;
import top.zbeboy.zone.domain.tables.records.CollegeRoleRecord;
import top.zbeboy.zone.domain.tables.records.CourseRecord;
import top.zbeboy.zone.domain.tables.records.CurriculumContentRecord;
import top.zbeboy.zone.domain.tables.records.CurriculumReleaseRecord;
import top.zbeboy.zone.domain.tables.records.DepartmentRecord;
import top.zbeboy.zone.domain.tables.records.FilesRecord;
import top.zbeboy.zone.domain.tables.records.GradeRecord;
import top.zbeboy.zone.domain.tables.records.NationRecord;
import top.zbeboy.zone.domain.tables.records.OrganizeRecord;
import top.zbeboy.zone.domain.tables.records.PoliticalLandscapeRecord;
import top.zbeboy.zone.domain.tables.records.QuestionFeedbackRecord;
import top.zbeboy.zone.domain.tables.records.RoleApplicationRecord;
import top.zbeboy.zone.domain.tables.records.RoleRecord;
import top.zbeboy.zone.domain.tables.records.SchoolRecord;
import top.zbeboy.zone.domain.tables.records.SchoolroomRecord;
import top.zbeboy.zone.domain.tables.records.ScienceRecord;
import top.zbeboy.zone.domain.tables.records.StaffRecord;
import top.zbeboy.zone.domain.tables.records.StudentRecord;
import top.zbeboy.zone.domain.tables.records.SystemConfigureRecord;
import top.zbeboy.zone.domain.tables.records.SystemMailboxLogRecord;
import top.zbeboy.zone.domain.tables.records.SystemNotifyRecord;
import top.zbeboy.zone.domain.tables.records.SystemOperatorLogRecord;
import top.zbeboy.zone.domain.tables.records.SystemSmsLogRecord;
import top.zbeboy.zone.domain.tables.records.TrainingAttendAuthoritiesRecord;
import top.zbeboy.zone.domain.tables.records.TrainingAttendLeaveApplyRecord;
import top.zbeboy.zone.domain.tables.records.TrainingAttendRecord;
import top.zbeboy.zone.domain.tables.records.TrainingAttendUsersRecord;
import top.zbeboy.zone.domain.tables.records.TrainingLabsRecord;
import top.zbeboy.zone.domain.tables.records.TrainingReleaseRecord;
import top.zbeboy.zone.domain.tables.records.TrainingUsersRecord;
import top.zbeboy.zone.domain.tables.records.UserNotifyRecord;
import top.zbeboy.zone.domain.tables.records.UsersRecord;
import top.zbeboy.zone.domain.tables.records.UsersTypeRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>zhe</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AcademicTitleRecord, Integer> IDENTITY_ACADEMIC_TITLE = Identities0.IDENTITY_ACADEMIC_TITLE;
    public static final Identity<AchievementSyncManifestRecord, Integer> IDENTITY_ACHIEVEMENT_SYNC_MANIFEST = Identities0.IDENTITY_ACHIEVEMENT_SYNC_MANIFEST;
    public static final Identity<CollegeRecord, Integer> IDENTITY_COLLEGE = Identities0.IDENTITY_COLLEGE;
    public static final Identity<DepartmentRecord, Integer> IDENTITY_DEPARTMENT = Identities0.IDENTITY_DEPARTMENT;
    public static final Identity<GradeRecord, Integer> IDENTITY_GRADE = Identities0.IDENTITY_GRADE;
    public static final Identity<NationRecord, Integer> IDENTITY_NATION = Identities0.IDENTITY_NATION;
    public static final Identity<OrganizeRecord, Integer> IDENTITY_ORGANIZE = Identities0.IDENTITY_ORGANIZE;
    public static final Identity<PoliticalLandscapeRecord, Integer> IDENTITY_POLITICAL_LANDSCAPE = Identities0.IDENTITY_POLITICAL_LANDSCAPE;
    public static final Identity<SchoolRecord, Integer> IDENTITY_SCHOOL = Identities0.IDENTITY_SCHOOL;
    public static final Identity<ScienceRecord, Integer> IDENTITY_SCIENCE = Identities0.IDENTITY_SCIENCE;
    public static final Identity<StaffRecord, Integer> IDENTITY_STAFF = Identities0.IDENTITY_STAFF;
    public static final Identity<StudentRecord, Integer> IDENTITY_STUDENT = Identities0.IDENTITY_STUDENT;
    public static final Identity<UsersTypeRecord, Integer> IDENTITY_USERS_TYPE = Identities0.IDENTITY_USERS_TYPE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AcademicTitleRecord> KEY_ACADEMIC_TITLE_PRIMARY = UniqueKeys0.KEY_ACADEMIC_TITLE_PRIMARY;
    public static final UniqueKey<AchievementReleaseRecord> KEY_ACHIEVEMENT_RELEASE_PRIMARY = UniqueKeys0.KEY_ACHIEVEMENT_RELEASE_PRIMARY;
    public static final UniqueKey<AchievementSyncDataRecord> KEY_ACHIEVEMENT_SYNC_DATA_COURSE_CODE = UniqueKeys0.KEY_ACHIEVEMENT_SYNC_DATA_COURSE_CODE;
    public static final UniqueKey<AchievementSyncManifestRecord> KEY_ACHIEVEMENT_SYNC_MANIFEST_PRIMARY = UniqueKeys0.KEY_ACHIEVEMENT_SYNC_MANIFEST_PRIMARY;
    public static final UniqueKey<AchievementSyncStudentRecord> KEY_ACHIEVEMENT_SYNC_STUDENT_PRIMARY = UniqueKeys0.KEY_ACHIEVEMENT_SYNC_STUDENT_PRIMARY;
    public static final UniqueKey<ApplicationRecord> KEY_APPLICATION_PRIMARY = UniqueKeys0.KEY_APPLICATION_PRIMARY;
    public static final UniqueKey<AuthoritiesRecord> KEY_AUTHORITIES_PRIMARY = UniqueKeys0.KEY_AUTHORITIES_PRIMARY;
    public static final UniqueKey<BuildingRecord> KEY_BUILDING_PRIMARY = UniqueKeys0.KEY_BUILDING_PRIMARY;
    public static final UniqueKey<CollegeRecord> KEY_COLLEGE_PRIMARY = UniqueKeys0.KEY_COLLEGE_PRIMARY;
    public static final UniqueKey<CollegeRecord> KEY_COLLEGE_COLLEGE_CODE = UniqueKeys0.KEY_COLLEGE_COLLEGE_CODE;
    public static final UniqueKey<CollegeApplicationRecord> KEY_COLLEGE_APPLICATION_PRIMARY = UniqueKeys0.KEY_COLLEGE_APPLICATION_PRIMARY;
    public static final UniqueKey<CollegeRoleRecord> KEY_COLLEGE_ROLE_PRIMARY = UniqueKeys0.KEY_COLLEGE_ROLE_PRIMARY;
    public static final UniqueKey<CourseRecord> KEY_COURSE_PRIMARY = UniqueKeys0.KEY_COURSE_PRIMARY;
    public static final UniqueKey<CourseRecord> KEY_COURSE_COURSE_CODE = UniqueKeys0.KEY_COURSE_COURSE_CODE;
    public static final UniqueKey<CurriculumContentRecord> KEY_CURRICULUM_CONTENT_PRIMARY = UniqueKeys0.KEY_CURRICULUM_CONTENT_PRIMARY;
    public static final UniqueKey<CurriculumReleaseRecord> KEY_CURRICULUM_RELEASE_PRIMARY = UniqueKeys0.KEY_CURRICULUM_RELEASE_PRIMARY;
    public static final UniqueKey<DepartmentRecord> KEY_DEPARTMENT_PRIMARY = UniqueKeys0.KEY_DEPARTMENT_PRIMARY;
    public static final UniqueKey<FilesRecord> KEY_FILES_PRIMARY = UniqueKeys0.KEY_FILES_PRIMARY;
    public static final UniqueKey<GradeRecord> KEY_GRADE_PRIMARY = UniqueKeys0.KEY_GRADE_PRIMARY;
    public static final UniqueKey<NationRecord> KEY_NATION_PRIMARY = UniqueKeys0.KEY_NATION_PRIMARY;
    public static final UniqueKey<OrganizeRecord> KEY_ORGANIZE_PRIMARY = UniqueKeys0.KEY_ORGANIZE_PRIMARY;
    public static final UniqueKey<PoliticalLandscapeRecord> KEY_POLITICAL_LANDSCAPE_PRIMARY = UniqueKeys0.KEY_POLITICAL_LANDSCAPE_PRIMARY;
    public static final UniqueKey<QuestionFeedbackRecord> KEY_QUESTION_FEEDBACK_PRIMARY = UniqueKeys0.KEY_QUESTION_FEEDBACK_PRIMARY;
    public static final UniqueKey<RoleRecord> KEY_ROLE_PRIMARY = UniqueKeys0.KEY_ROLE_PRIMARY;
    public static final UniqueKey<RoleRecord> KEY_ROLE_ROLE_EN_NAME = UniqueKeys0.KEY_ROLE_ROLE_EN_NAME;
    public static final UniqueKey<RoleApplicationRecord> KEY_ROLE_APPLICATION_PRIMARY = UniqueKeys0.KEY_ROLE_APPLICATION_PRIMARY;
    public static final UniqueKey<SchoolRecord> KEY_SCHOOL_PRIMARY = UniqueKeys0.KEY_SCHOOL_PRIMARY;
    public static final UniqueKey<SchoolroomRecord> KEY_SCHOOLROOM_PRIMARY = UniqueKeys0.KEY_SCHOOLROOM_PRIMARY;
    public static final UniqueKey<ScienceRecord> KEY_SCIENCE_PRIMARY = UniqueKeys0.KEY_SCIENCE_PRIMARY;
    public static final UniqueKey<ScienceRecord> KEY_SCIENCE_SCIENCE_CODE = UniqueKeys0.KEY_SCIENCE_SCIENCE_CODE;
    public static final UniqueKey<StaffRecord> KEY_STAFF_PRIMARY = UniqueKeys0.KEY_STAFF_PRIMARY;
    public static final UniqueKey<StaffRecord> KEY_STAFF_STAFF_NUMBER = UniqueKeys0.KEY_STAFF_STAFF_NUMBER;
    public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = UniqueKeys0.KEY_STUDENT_PRIMARY;
    public static final UniqueKey<StudentRecord> KEY_STUDENT_STUDENT_NUMBER = UniqueKeys0.KEY_STUDENT_STUDENT_NUMBER;
    public static final UniqueKey<SystemConfigureRecord> KEY_SYSTEM_CONFIGURE_PRIMARY = UniqueKeys0.KEY_SYSTEM_CONFIGURE_PRIMARY;
    public static final UniqueKey<SystemMailboxLogRecord> KEY_SYSTEM_MAILBOX_LOG_PRIMARY = UniqueKeys0.KEY_SYSTEM_MAILBOX_LOG_PRIMARY;
    public static final UniqueKey<SystemNotifyRecord> KEY_SYSTEM_NOTIFY_PRIMARY = UniqueKeys0.KEY_SYSTEM_NOTIFY_PRIMARY;
    public static final UniqueKey<SystemOperatorLogRecord> KEY_SYSTEM_OPERATOR_LOG_PRIMARY = UniqueKeys0.KEY_SYSTEM_OPERATOR_LOG_PRIMARY;
    public static final UniqueKey<SystemSmsLogRecord> KEY_SYSTEM_SMS_LOG_PRIMARY = UniqueKeys0.KEY_SYSTEM_SMS_LOG_PRIMARY;
    public static final UniqueKey<TrainingAttendRecord> KEY_TRAINING_ATTEND_PRIMARY = UniqueKeys0.KEY_TRAINING_ATTEND_PRIMARY;
    public static final UniqueKey<TrainingAttendAuthoritiesRecord> KEY_TRAINING_ATTEND_AUTHORITIES_PRIMARY = UniqueKeys0.KEY_TRAINING_ATTEND_AUTHORITIES_PRIMARY;
    public static final UniqueKey<TrainingAttendLeaveApplyRecord> KEY_TRAINING_ATTEND_LEAVE_APPLY_PRIMARY = UniqueKeys0.KEY_TRAINING_ATTEND_LEAVE_APPLY_PRIMARY;
    public static final UniqueKey<TrainingAttendLeaveApplyRecord> KEY_TRAINING_ATTEND_LEAVE_APPLY_TRAINING_ATTEND_ID = UniqueKeys0.KEY_TRAINING_ATTEND_LEAVE_APPLY_TRAINING_ATTEND_ID;
    public static final UniqueKey<TrainingAttendUsersRecord> KEY_TRAINING_ATTEND_USERS_PRIMARY = UniqueKeys0.KEY_TRAINING_ATTEND_USERS_PRIMARY;
    public static final UniqueKey<TrainingAttendUsersRecord> KEY_TRAINING_ATTEND_USERS_TRAINING_ATTEND_ID = UniqueKeys0.KEY_TRAINING_ATTEND_USERS_TRAINING_ATTEND_ID;
    public static final UniqueKey<TrainingLabsRecord> KEY_TRAINING_LABS_PRIMARY = UniqueKeys0.KEY_TRAINING_LABS_PRIMARY;
    public static final UniqueKey<TrainingLabsRecord> KEY_TRAINING_LABS_STUDENT_NUMBER = UniqueKeys0.KEY_TRAINING_LABS_STUDENT_NUMBER;
    public static final UniqueKey<TrainingReleaseRecord> KEY_TRAINING_RELEASE_PRIMARY = UniqueKeys0.KEY_TRAINING_RELEASE_PRIMARY;
    public static final UniqueKey<TrainingUsersRecord> KEY_TRAINING_USERS_PRIMARY = UniqueKeys0.KEY_TRAINING_USERS_PRIMARY;
    public static final UniqueKey<TrainingUsersRecord> KEY_TRAINING_USERS_TRAINING_RELEASE_ID = UniqueKeys0.KEY_TRAINING_USERS_TRAINING_RELEASE_ID;
    public static final UniqueKey<UserNotifyRecord> KEY_USER_NOTIFY_PRIMARY = UniqueKeys0.KEY_USER_NOTIFY_PRIMARY;
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;
    public static final UniqueKey<UsersRecord> KEY_USERS_EMAIL = UniqueKeys0.KEY_USERS_EMAIL;
    public static final UniqueKey<UsersRecord> KEY_USERS_MOBILE = UniqueKeys0.KEY_USERS_MOBILE;
    public static final UniqueKey<UsersTypeRecord> KEY_USERS_TYPE_PRIMARY = UniqueKeys0.KEY_USERS_TYPE_PRIMARY;
    public static final UniqueKey<UsersTypeRecord> KEY_USERS_TYPE_USERS_TYPE_NAME = UniqueKeys0.KEY_USERS_TYPE_USERS_TYPE_NAME;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AchievementReleaseRecord, DepartmentRecord> ACHIEVEMENT_RELEASE_IBFK_1 = ForeignKeys0.ACHIEVEMENT_RELEASE_IBFK_1;
    public static final ForeignKey<AchievementReleaseRecord, UsersRecord> ACHIEVEMENT_RELEASE_IBFK_2 = ForeignKeys0.ACHIEVEMENT_RELEASE_IBFK_2;
    public static final ForeignKey<AchievementSyncManifestRecord, AchievementReleaseRecord> ACHIEVEMENT_SYNC_MANIFEST_IBFK_1 = ForeignKeys0.ACHIEVEMENT_SYNC_MANIFEST_IBFK_1;
    public static final ForeignKey<AuthoritiesRecord, UsersRecord> AUTHORITIES_IBFK_1 = ForeignKeys0.AUTHORITIES_IBFK_1;
    public static final ForeignKey<BuildingRecord, CollegeRecord> BUILDING_IBFK_1 = ForeignKeys0.BUILDING_IBFK_1;
    public static final ForeignKey<CollegeRecord, SchoolRecord> COLLEGE_IBFK_1 = ForeignKeys0.COLLEGE_IBFK_1;
    public static final ForeignKey<CollegeApplicationRecord, ApplicationRecord> COLLEGE_APPLICATION_IBFK_1 = ForeignKeys0.COLLEGE_APPLICATION_IBFK_1;
    public static final ForeignKey<CollegeApplicationRecord, CollegeRecord> COLLEGE_APPLICATION_IBFK_2 = ForeignKeys0.COLLEGE_APPLICATION_IBFK_2;
    public static final ForeignKey<CollegeRoleRecord, RoleRecord> COLLEGE_ROLE_IBFK_1 = ForeignKeys0.COLLEGE_ROLE_IBFK_1;
    public static final ForeignKey<CollegeRoleRecord, CollegeRecord> COLLEGE_ROLE_IBFK_2 = ForeignKeys0.COLLEGE_ROLE_IBFK_2;
    public static final ForeignKey<CourseRecord, CollegeRecord> COURSE_IBFK_1 = ForeignKeys0.COURSE_IBFK_1;
    public static final ForeignKey<CurriculumContentRecord, CurriculumReleaseRecord> CURRICULUM_CONTENT_IBFK_1 = ForeignKeys0.CURRICULUM_CONTENT_IBFK_1;
    public static final ForeignKey<CurriculumContentRecord, UsersRecord> CURRICULUM_CONTENT_IBFK_2 = ForeignKeys0.CURRICULUM_CONTENT_IBFK_2;
    public static final ForeignKey<CurriculumReleaseRecord, CollegeRecord> CURRICULUM_RELEASE_IBFK_1 = ForeignKeys0.CURRICULUM_RELEASE_IBFK_1;
    public static final ForeignKey<CurriculumReleaseRecord, UsersRecord> CURRICULUM_RELEASE_IBFK_2 = ForeignKeys0.CURRICULUM_RELEASE_IBFK_2;
    public static final ForeignKey<DepartmentRecord, CollegeRecord> DEPARTMENT_IBFK_1 = ForeignKeys0.DEPARTMENT_IBFK_1;
    public static final ForeignKey<GradeRecord, ScienceRecord> GRADE_IBFK_1 = ForeignKeys0.GRADE_IBFK_1;
    public static final ForeignKey<OrganizeRecord, GradeRecord> ORGANIZE_IBFK_1 = ForeignKeys0.ORGANIZE_IBFK_1;
    public static final ForeignKey<RoleApplicationRecord, RoleRecord> ROLE_APPLICATION_IBFK_1 = ForeignKeys0.ROLE_APPLICATION_IBFK_1;
    public static final ForeignKey<RoleApplicationRecord, ApplicationRecord> ROLE_APPLICATION_IBFK_2 = ForeignKeys0.ROLE_APPLICATION_IBFK_2;
    public static final ForeignKey<SchoolroomRecord, BuildingRecord> SCHOOLROOM_IBFK_1 = ForeignKeys0.SCHOOLROOM_IBFK_1;
    public static final ForeignKey<ScienceRecord, DepartmentRecord> SCIENCE_IBFK_1 = ForeignKeys0.SCIENCE_IBFK_1;
    public static final ForeignKey<StaffRecord, DepartmentRecord> STAFF_IBFK_1 = ForeignKeys0.STAFF_IBFK_1;
    public static final ForeignKey<StaffRecord, UsersRecord> STAFF_IBFK_2 = ForeignKeys0.STAFF_IBFK_2;
    public static final ForeignKey<StudentRecord, OrganizeRecord> STUDENT_IBFK_1 = ForeignKeys0.STUDENT_IBFK_1;
    public static final ForeignKey<StudentRecord, UsersRecord> STUDENT_IBFK_2 = ForeignKeys0.STUDENT_IBFK_2;
    public static final ForeignKey<SystemNotifyRecord, UsersRecord> SYSTEM_NOTIFY_IBFK_1 = ForeignKeys0.SYSTEM_NOTIFY_IBFK_1;
    public static final ForeignKey<TrainingAttendRecord, SchoolroomRecord> TRAINING_ATTEND_IBFK_1 = ForeignKeys0.TRAINING_ATTEND_IBFK_1;
    public static final ForeignKey<TrainingAttendRecord, TrainingReleaseRecord> TRAINING_ATTEND_IBFK_2 = ForeignKeys0.TRAINING_ATTEND_IBFK_2;
    public static final ForeignKey<TrainingAttendAuthoritiesRecord, TrainingAttendRecord> TRAINING_ATTEND_AUTHORITIES_IBFK_1 = ForeignKeys0.TRAINING_ATTEND_AUTHORITIES_IBFK_1;
    public static final ForeignKey<TrainingAttendAuthoritiesRecord, UsersRecord> TRAINING_ATTEND_AUTHORITIES_IBFK_2 = ForeignKeys0.TRAINING_ATTEND_AUTHORITIES_IBFK_2;
    public static final ForeignKey<TrainingAttendLeaveApplyRecord, TrainingAttendRecord> TRAINING_ATTEND_LEAVE_APPLY_IBFK_1 = ForeignKeys0.TRAINING_ATTEND_LEAVE_APPLY_IBFK_1;
    public static final ForeignKey<TrainingAttendLeaveApplyRecord, TrainingUsersRecord> TRAINING_ATTEND_LEAVE_APPLY_IBFK_2 = ForeignKeys0.TRAINING_ATTEND_LEAVE_APPLY_IBFK_2;
    public static final ForeignKey<TrainingAttendUsersRecord, TrainingAttendRecord> TRAINING_ATTEND_USERS_IBFK_1 = ForeignKeys0.TRAINING_ATTEND_USERS_IBFK_1;
    public static final ForeignKey<TrainingAttendUsersRecord, TrainingUsersRecord> TRAINING_ATTEND_USERS_IBFK_2 = ForeignKeys0.TRAINING_ATTEND_USERS_IBFK_2;
    public static final ForeignKey<TrainingReleaseRecord, SchoolroomRecord> TRAINING_RELEASE_IBFK_1 = ForeignKeys0.TRAINING_RELEASE_IBFK_1;
    public static final ForeignKey<TrainingReleaseRecord, UsersRecord> TRAINING_RELEASE_IBFK_2 = ForeignKeys0.TRAINING_RELEASE_IBFK_2;
    public static final ForeignKey<TrainingReleaseRecord, CourseRecord> TRAINING_RELEASE_IBFK_3 = ForeignKeys0.TRAINING_RELEASE_IBFK_3;
    public static final ForeignKey<TrainingReleaseRecord, OrganizeRecord> TRAINING_RELEASE_IBFK_4 = ForeignKeys0.TRAINING_RELEASE_IBFK_4;
    public static final ForeignKey<TrainingUsersRecord, TrainingReleaseRecord> TRAINING_USERS_IBFK_1 = ForeignKeys0.TRAINING_USERS_IBFK_1;
    public static final ForeignKey<TrainingUsersRecord, StudentRecord> TRAINING_USERS_IBFK_2 = ForeignKeys0.TRAINING_USERS_IBFK_2;
    public static final ForeignKey<UserNotifyRecord, UsersRecord> USER_NOTIFY_IBFK_1 = ForeignKeys0.USER_NOTIFY_IBFK_1;
    public static final ForeignKey<UserNotifyRecord, UsersRecord> USER_NOTIFY_IBFK_2 = ForeignKeys0.USER_NOTIFY_IBFK_2;
    public static final ForeignKey<UsersRecord, UsersTypeRecord> USERS_IBFK_1 = ForeignKeys0.USERS_IBFK_1;
    public static final ForeignKey<UsersRecord, FilesRecord> USERS_IBFK_2 = ForeignKeys0.USERS_IBFK_2;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AcademicTitleRecord, Integer> IDENTITY_ACADEMIC_TITLE = Internal.createIdentity(AcademicTitle.ACADEMIC_TITLE, AcademicTitle.ACADEMIC_TITLE.ACADEMIC_TITLE_ID);
        public static Identity<AchievementSyncManifestRecord, Integer> IDENTITY_ACHIEVEMENT_SYNC_MANIFEST = Internal.createIdentity(AchievementSyncManifest.ACHIEVEMENT_SYNC_MANIFEST, AchievementSyncManifest.ACHIEVEMENT_SYNC_MANIFEST.MANIFEST_ID);
        public static Identity<CollegeRecord, Integer> IDENTITY_COLLEGE = Internal.createIdentity(College.COLLEGE, College.COLLEGE.COLLEGE_ID);
        public static Identity<DepartmentRecord, Integer> IDENTITY_DEPARTMENT = Internal.createIdentity(Department.DEPARTMENT, Department.DEPARTMENT.DEPARTMENT_ID);
        public static Identity<GradeRecord, Integer> IDENTITY_GRADE = Internal.createIdentity(Grade.GRADE, Grade.GRADE.GRADE_ID);
        public static Identity<NationRecord, Integer> IDENTITY_NATION = Internal.createIdentity(Nation.NATION, Nation.NATION.NATION_ID);
        public static Identity<OrganizeRecord, Integer> IDENTITY_ORGANIZE = Internal.createIdentity(Organize.ORGANIZE, Organize.ORGANIZE.ORGANIZE_ID);
        public static Identity<PoliticalLandscapeRecord, Integer> IDENTITY_POLITICAL_LANDSCAPE = Internal.createIdentity(PoliticalLandscape.POLITICAL_LANDSCAPE, PoliticalLandscape.POLITICAL_LANDSCAPE.POLITICAL_LANDSCAPE_ID);
        public static Identity<SchoolRecord, Integer> IDENTITY_SCHOOL = Internal.createIdentity(School.SCHOOL, School.SCHOOL.SCHOOL_ID);
        public static Identity<ScienceRecord, Integer> IDENTITY_SCIENCE = Internal.createIdentity(Science.SCIENCE, Science.SCIENCE.SCIENCE_ID);
        public static Identity<StaffRecord, Integer> IDENTITY_STAFF = Internal.createIdentity(Staff.STAFF, Staff.STAFF.STAFF_ID);
        public static Identity<StudentRecord, Integer> IDENTITY_STUDENT = Internal.createIdentity(Student.STUDENT, Student.STUDENT.STUDENT_ID);
        public static Identity<UsersTypeRecord, Integer> IDENTITY_USERS_TYPE = Internal.createIdentity(UsersType.USERS_TYPE, UsersType.USERS_TYPE.USERS_TYPE_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AcademicTitleRecord> KEY_ACADEMIC_TITLE_PRIMARY = Internal.createUniqueKey(AcademicTitle.ACADEMIC_TITLE, "KEY_academic_title_PRIMARY", AcademicTitle.ACADEMIC_TITLE.ACADEMIC_TITLE_ID);
        public static final UniqueKey<AchievementReleaseRecord> KEY_ACHIEVEMENT_RELEASE_PRIMARY = Internal.createUniqueKey(AchievementRelease.ACHIEVEMENT_RELEASE, "KEY_achievement_release_PRIMARY", AchievementRelease.ACHIEVEMENT_RELEASE.ACHIEVEMENT_RELEASE_ID);
        public static final UniqueKey<AchievementSyncDataRecord> KEY_ACHIEVEMENT_SYNC_DATA_COURSE_CODE = Internal.createUniqueKey(AchievementSyncData.ACHIEVEMENT_SYNC_DATA, "KEY_achievement_sync_data_course_code", AchievementSyncData.ACHIEVEMENT_SYNC_DATA.COURSE_CODE, AchievementSyncData.ACHIEVEMENT_SYNC_DATA.SCORE, AchievementSyncData.ACHIEVEMENT_SYNC_DATA.ROTATION, AchievementSyncData.ACHIEVEMENT_SYNC_DATA.STUDENT_NUMBER);
        public static final UniqueKey<AchievementSyncManifestRecord> KEY_ACHIEVEMENT_SYNC_MANIFEST_PRIMARY = Internal.createUniqueKey(AchievementSyncManifest.ACHIEVEMENT_SYNC_MANIFEST, "KEY_achievement_sync_manifest_PRIMARY", AchievementSyncManifest.ACHIEVEMENT_SYNC_MANIFEST.MANIFEST_ID);
        public static final UniqueKey<AchievementSyncStudentRecord> KEY_ACHIEVEMENT_SYNC_STUDENT_PRIMARY = Internal.createUniqueKey(AchievementSyncStudent.ACHIEVEMENT_SYNC_STUDENT, "KEY_achievement_sync_student_PRIMARY", AchievementSyncStudent.ACHIEVEMENT_SYNC_STUDENT.STUDENT_NUMBER);
        public static final UniqueKey<ApplicationRecord> KEY_APPLICATION_PRIMARY = Internal.createUniqueKey(Application.APPLICATION, "KEY_application_PRIMARY", Application.APPLICATION.APPLICATION_ID);
        public static final UniqueKey<AuthoritiesRecord> KEY_AUTHORITIES_PRIMARY = Internal.createUniqueKey(Authorities.AUTHORITIES, "KEY_authorities_PRIMARY", Authorities.AUTHORITIES.USERNAME, Authorities.AUTHORITIES.AUTHORITY);
        public static final UniqueKey<BuildingRecord> KEY_BUILDING_PRIMARY = Internal.createUniqueKey(Building.BUILDING, "KEY_building_PRIMARY", Building.BUILDING.BUILDING_ID);
        public static final UniqueKey<CollegeRecord> KEY_COLLEGE_PRIMARY = Internal.createUniqueKey(College.COLLEGE, "KEY_college_PRIMARY", College.COLLEGE.COLLEGE_ID);
        public static final UniqueKey<CollegeRecord> KEY_COLLEGE_COLLEGE_CODE = Internal.createUniqueKey(College.COLLEGE, "KEY_college_college_code", College.COLLEGE.COLLEGE_CODE);
        public static final UniqueKey<CollegeApplicationRecord> KEY_COLLEGE_APPLICATION_PRIMARY = Internal.createUniqueKey(CollegeApplication.COLLEGE_APPLICATION, "KEY_college_application_PRIMARY", CollegeApplication.COLLEGE_APPLICATION.APPLICATION_ID, CollegeApplication.COLLEGE_APPLICATION.COLLEGE_ID);
        public static final UniqueKey<CollegeRoleRecord> KEY_COLLEGE_ROLE_PRIMARY = Internal.createUniqueKey(CollegeRole.COLLEGE_ROLE, "KEY_college_role_PRIMARY", CollegeRole.COLLEGE_ROLE.ROLE_ID, CollegeRole.COLLEGE_ROLE.COLLEGE_ID);
        public static final UniqueKey<CourseRecord> KEY_COURSE_PRIMARY = Internal.createUniqueKey(Course.COURSE, "KEY_course_PRIMARY", Course.COURSE.COURSE_ID);
        public static final UniqueKey<CourseRecord> KEY_COURSE_COURSE_CODE = Internal.createUniqueKey(Course.COURSE, "KEY_course_course_code", Course.COURSE.COURSE_CODE);
        public static final UniqueKey<CurriculumContentRecord> KEY_CURRICULUM_CONTENT_PRIMARY = Internal.createUniqueKey(CurriculumContent.CURRICULUM_CONTENT, "KEY_curriculum_content_PRIMARY", CurriculumContent.CURRICULUM_CONTENT.CURRICULUM_RELEASE_ID, CurriculumContent.CURRICULUM_CONTENT.SCHOOLROOM_NAME, CurriculumContent.CURRICULUM_CONTENT.WEEK, CurriculumContent.CURRICULUM_CONTENT.BATCH_NUM);
        public static final UniqueKey<CurriculumReleaseRecord> KEY_CURRICULUM_RELEASE_PRIMARY = Internal.createUniqueKey(CurriculumRelease.CURRICULUM_RELEASE, "KEY_curriculum_release_PRIMARY", CurriculumRelease.CURRICULUM_RELEASE.CURRICULUM_RELEASE_ID);
        public static final UniqueKey<DepartmentRecord> KEY_DEPARTMENT_PRIMARY = Internal.createUniqueKey(Department.DEPARTMENT, "KEY_department_PRIMARY", Department.DEPARTMENT.DEPARTMENT_ID);
        public static final UniqueKey<FilesRecord> KEY_FILES_PRIMARY = Internal.createUniqueKey(Files.FILES, "KEY_files_PRIMARY", Files.FILES.FILE_ID);
        public static final UniqueKey<GradeRecord> KEY_GRADE_PRIMARY = Internal.createUniqueKey(Grade.GRADE, "KEY_grade_PRIMARY", Grade.GRADE.GRADE_ID);
        public static final UniqueKey<NationRecord> KEY_NATION_PRIMARY = Internal.createUniqueKey(Nation.NATION, "KEY_nation_PRIMARY", Nation.NATION.NATION_ID);
        public static final UniqueKey<OrganizeRecord> KEY_ORGANIZE_PRIMARY = Internal.createUniqueKey(Organize.ORGANIZE, "KEY_organize_PRIMARY", Organize.ORGANIZE.ORGANIZE_ID);
        public static final UniqueKey<PoliticalLandscapeRecord> KEY_POLITICAL_LANDSCAPE_PRIMARY = Internal.createUniqueKey(PoliticalLandscape.POLITICAL_LANDSCAPE, "KEY_political_landscape_PRIMARY", PoliticalLandscape.POLITICAL_LANDSCAPE.POLITICAL_LANDSCAPE_ID);
        public static final UniqueKey<QuestionFeedbackRecord> KEY_QUESTION_FEEDBACK_PRIMARY = Internal.createUniqueKey(QuestionFeedback.QUESTION_FEEDBACK, "KEY_question_feedback_PRIMARY", QuestionFeedback.QUESTION_FEEDBACK.FEEDBACK_ID);
        public static final UniqueKey<RoleRecord> KEY_ROLE_PRIMARY = Internal.createUniqueKey(Role.ROLE, "KEY_role_PRIMARY", Role.ROLE.ROLE_ID);
        public static final UniqueKey<RoleRecord> KEY_ROLE_ROLE_EN_NAME = Internal.createUniqueKey(Role.ROLE, "KEY_role_role_en_name", Role.ROLE.ROLE_EN_NAME);
        public static final UniqueKey<RoleApplicationRecord> KEY_ROLE_APPLICATION_PRIMARY = Internal.createUniqueKey(RoleApplication.ROLE_APPLICATION, "KEY_role_application_PRIMARY", RoleApplication.ROLE_APPLICATION.ROLE_ID, RoleApplication.ROLE_APPLICATION.APPLICATION_ID);
        public static final UniqueKey<SchoolRecord> KEY_SCHOOL_PRIMARY = Internal.createUniqueKey(School.SCHOOL, "KEY_school_PRIMARY", School.SCHOOL.SCHOOL_ID);
        public static final UniqueKey<SchoolroomRecord> KEY_SCHOOLROOM_PRIMARY = Internal.createUniqueKey(Schoolroom.SCHOOLROOM, "KEY_schoolroom_PRIMARY", Schoolroom.SCHOOLROOM.SCHOOLROOM_ID);
        public static final UniqueKey<ScienceRecord> KEY_SCIENCE_PRIMARY = Internal.createUniqueKey(Science.SCIENCE, "KEY_science_PRIMARY", Science.SCIENCE.SCIENCE_ID);
        public static final UniqueKey<ScienceRecord> KEY_SCIENCE_SCIENCE_CODE = Internal.createUniqueKey(Science.SCIENCE, "KEY_science_science_code", Science.SCIENCE.SCIENCE_CODE);
        public static final UniqueKey<StaffRecord> KEY_STAFF_PRIMARY = Internal.createUniqueKey(Staff.STAFF, "KEY_staff_PRIMARY", Staff.STAFF.STAFF_ID);
        public static final UniqueKey<StaffRecord> KEY_STAFF_STAFF_NUMBER = Internal.createUniqueKey(Staff.STAFF, "KEY_staff_staff_number", Staff.STAFF.STAFF_NUMBER);
        public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = Internal.createUniqueKey(Student.STUDENT, "KEY_student_PRIMARY", Student.STUDENT.STUDENT_ID);
        public static final UniqueKey<StudentRecord> KEY_STUDENT_STUDENT_NUMBER = Internal.createUniqueKey(Student.STUDENT, "KEY_student_student_number", Student.STUDENT.STUDENT_NUMBER);
        public static final UniqueKey<SystemConfigureRecord> KEY_SYSTEM_CONFIGURE_PRIMARY = Internal.createUniqueKey(SystemConfigure.SYSTEM_CONFIGURE, "KEY_system_configure_PRIMARY", SystemConfigure.SYSTEM_CONFIGURE.DATA_KEY);
        public static final UniqueKey<SystemMailboxLogRecord> KEY_SYSTEM_MAILBOX_LOG_PRIMARY = Internal.createUniqueKey(SystemMailboxLog.SYSTEM_MAILBOX_LOG, "KEY_system_mailbox_log_PRIMARY", SystemMailboxLog.SYSTEM_MAILBOX_LOG.LOG_ID);
        public static final UniqueKey<SystemNotifyRecord> KEY_SYSTEM_NOTIFY_PRIMARY = Internal.createUniqueKey(SystemNotify.SYSTEM_NOTIFY, "KEY_system_notify_PRIMARY", SystemNotify.SYSTEM_NOTIFY.SYSTEM_NOTIFY_ID);
        public static final UniqueKey<SystemOperatorLogRecord> KEY_SYSTEM_OPERATOR_LOG_PRIMARY = Internal.createUniqueKey(SystemOperatorLog.SYSTEM_OPERATOR_LOG, "KEY_system_operator_log_PRIMARY", SystemOperatorLog.SYSTEM_OPERATOR_LOG.LOG_ID);
        public static final UniqueKey<SystemSmsLogRecord> KEY_SYSTEM_SMS_LOG_PRIMARY = Internal.createUniqueKey(SystemSmsLog.SYSTEM_SMS_LOG, "KEY_system_sms_log_PRIMARY", SystemSmsLog.SYSTEM_SMS_LOG.LOG_ID);
        public static final UniqueKey<TrainingAttendRecord> KEY_TRAINING_ATTEND_PRIMARY = Internal.createUniqueKey(TrainingAttend.TRAINING_ATTEND, "KEY_training_attend_PRIMARY", TrainingAttend.TRAINING_ATTEND.TRAINING_ATTEND_ID);
        public static final UniqueKey<TrainingAttendAuthoritiesRecord> KEY_TRAINING_ATTEND_AUTHORITIES_PRIMARY = Internal.createUniqueKey(TrainingAttendAuthorities.TRAINING_ATTEND_AUTHORITIES, "KEY_training_attend_authorities_PRIMARY", TrainingAttendAuthorities.TRAINING_ATTEND_AUTHORITIES.AUTHORITIES_ID);
        public static final UniqueKey<TrainingAttendLeaveApplyRecord> KEY_TRAINING_ATTEND_LEAVE_APPLY_PRIMARY = Internal.createUniqueKey(TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY, "KEY_training_attend_leave_apply_PRIMARY", TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY.LEAVE_APPLY_ID);
        public static final UniqueKey<TrainingAttendLeaveApplyRecord> KEY_TRAINING_ATTEND_LEAVE_APPLY_TRAINING_ATTEND_ID = Internal.createUniqueKey(TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY, "KEY_training_attend_leave_apply_training_attend_id", TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY.TRAINING_ATTEND_ID, TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY.TRAINING_USERS_ID);
        public static final UniqueKey<TrainingAttendUsersRecord> KEY_TRAINING_ATTEND_USERS_PRIMARY = Internal.createUniqueKey(TrainingAttendUsers.TRAINING_ATTEND_USERS, "KEY_training_attend_users_PRIMARY", TrainingAttendUsers.TRAINING_ATTEND_USERS.ATTEND_USERS_ID);
        public static final UniqueKey<TrainingAttendUsersRecord> KEY_TRAINING_ATTEND_USERS_TRAINING_ATTEND_ID = Internal.createUniqueKey(TrainingAttendUsers.TRAINING_ATTEND_USERS, "KEY_training_attend_users_training_attend_id", TrainingAttendUsers.TRAINING_ATTEND_USERS.TRAINING_ATTEND_ID, TrainingAttendUsers.TRAINING_ATTEND_USERS.TRAINING_USERS_ID);
        public static final UniqueKey<TrainingLabsRecord> KEY_TRAINING_LABS_PRIMARY = Internal.createUniqueKey(TrainingLabs.TRAINING_LABS, "KEY_training_labs_PRIMARY", TrainingLabs.TRAINING_LABS.TRAINING_LABS_ID);
        public static final UniqueKey<TrainingLabsRecord> KEY_TRAINING_LABS_STUDENT_NUMBER = Internal.createUniqueKey(TrainingLabs.TRAINING_LABS, "KEY_training_labs_student_number", TrainingLabs.TRAINING_LABS.STUDENT_NUMBER);
        public static final UniqueKey<TrainingReleaseRecord> KEY_TRAINING_RELEASE_PRIMARY = Internal.createUniqueKey(TrainingRelease.TRAINING_RELEASE, "KEY_training_release_PRIMARY", TrainingRelease.TRAINING_RELEASE.TRAINING_RELEASE_ID);
        public static final UniqueKey<TrainingUsersRecord> KEY_TRAINING_USERS_PRIMARY = Internal.createUniqueKey(TrainingUsers.TRAINING_USERS, "KEY_training_users_PRIMARY", TrainingUsers.TRAINING_USERS.TRAINING_USERS_ID);
        public static final UniqueKey<TrainingUsersRecord> KEY_TRAINING_USERS_TRAINING_RELEASE_ID = Internal.createUniqueKey(TrainingUsers.TRAINING_USERS, "KEY_training_users_training_release_id", TrainingUsers.TRAINING_USERS.TRAINING_RELEASE_ID, TrainingUsers.TRAINING_USERS.STUDENT_ID);
        public static final UniqueKey<UserNotifyRecord> KEY_USER_NOTIFY_PRIMARY = Internal.createUniqueKey(UserNotify.USER_NOTIFY, "KEY_user_notify_PRIMARY", UserNotify.USER_NOTIFY.USER_NOTIFY_ID);
        public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, "KEY_users_PRIMARY", Users.USERS.USERNAME);
        public static final UniqueKey<UsersRecord> KEY_USERS_EMAIL = Internal.createUniqueKey(Users.USERS, "KEY_users_email", Users.USERS.EMAIL);
        public static final UniqueKey<UsersRecord> KEY_USERS_MOBILE = Internal.createUniqueKey(Users.USERS, "KEY_users_mobile", Users.USERS.MOBILE);
        public static final UniqueKey<UsersTypeRecord> KEY_USERS_TYPE_PRIMARY = Internal.createUniqueKey(UsersType.USERS_TYPE, "KEY_users_type_PRIMARY", UsersType.USERS_TYPE.USERS_TYPE_ID);
        public static final UniqueKey<UsersTypeRecord> KEY_USERS_TYPE_USERS_TYPE_NAME = Internal.createUniqueKey(UsersType.USERS_TYPE, "KEY_users_type_users_type_name", UsersType.USERS_TYPE.USERS_TYPE_NAME);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AchievementReleaseRecord, DepartmentRecord> ACHIEVEMENT_RELEASE_IBFK_1 = Internal.createForeignKey(Keys.KEY_DEPARTMENT_PRIMARY, AchievementRelease.ACHIEVEMENT_RELEASE, "achievement_release_ibfk_1", AchievementRelease.ACHIEVEMENT_RELEASE.DEPARTMENT_ID);
        public static final ForeignKey<AchievementReleaseRecord, UsersRecord> ACHIEVEMENT_RELEASE_IBFK_2 = Internal.createForeignKey(Keys.KEY_USERS_PRIMARY, AchievementRelease.ACHIEVEMENT_RELEASE, "achievement_release_ibfk_2", AchievementRelease.ACHIEVEMENT_RELEASE.RELEASE_USERNAME);
        public static final ForeignKey<AchievementSyncManifestRecord, AchievementReleaseRecord> ACHIEVEMENT_SYNC_MANIFEST_IBFK_1 = Internal.createForeignKey(Keys.KEY_ACHIEVEMENT_RELEASE_PRIMARY, AchievementSyncManifest.ACHIEVEMENT_SYNC_MANIFEST, "achievement_sync_manifest_ibfk_1", AchievementSyncManifest.ACHIEVEMENT_SYNC_MANIFEST.ACHIEVEMENT_RELEASE_ID);
        public static final ForeignKey<AuthoritiesRecord, UsersRecord> AUTHORITIES_IBFK_1 = Internal.createForeignKey(Keys.KEY_USERS_PRIMARY, Authorities.AUTHORITIES, "authorities_ibfk_1", Authorities.AUTHORITIES.USERNAME);
        public static final ForeignKey<BuildingRecord, CollegeRecord> BUILDING_IBFK_1 = Internal.createForeignKey(Keys.KEY_COLLEGE_PRIMARY, Building.BUILDING, "building_ibfk_1", Building.BUILDING.COLLEGE_ID);
        public static final ForeignKey<CollegeRecord, SchoolRecord> COLLEGE_IBFK_1 = Internal.createForeignKey(Keys.KEY_SCHOOL_PRIMARY, College.COLLEGE, "college_ibfk_1", College.COLLEGE.SCHOOL_ID);
        public static final ForeignKey<CollegeApplicationRecord, ApplicationRecord> COLLEGE_APPLICATION_IBFK_1 = Internal.createForeignKey(Keys.KEY_APPLICATION_PRIMARY, CollegeApplication.COLLEGE_APPLICATION, "college_application_ibfk_1", CollegeApplication.COLLEGE_APPLICATION.APPLICATION_ID);
        public static final ForeignKey<CollegeApplicationRecord, CollegeRecord> COLLEGE_APPLICATION_IBFK_2 = Internal.createForeignKey(Keys.KEY_COLLEGE_PRIMARY, CollegeApplication.COLLEGE_APPLICATION, "college_application_ibfk_2", CollegeApplication.COLLEGE_APPLICATION.COLLEGE_ID);
        public static final ForeignKey<CollegeRoleRecord, RoleRecord> COLLEGE_ROLE_IBFK_1 = Internal.createForeignKey(Keys.KEY_ROLE_PRIMARY, CollegeRole.COLLEGE_ROLE, "college_role_ibfk_1", CollegeRole.COLLEGE_ROLE.ROLE_ID);
        public static final ForeignKey<CollegeRoleRecord, CollegeRecord> COLLEGE_ROLE_IBFK_2 = Internal.createForeignKey(Keys.KEY_COLLEGE_PRIMARY, CollegeRole.COLLEGE_ROLE, "college_role_ibfk_2", CollegeRole.COLLEGE_ROLE.COLLEGE_ID);
        public static final ForeignKey<CourseRecord, CollegeRecord> COURSE_IBFK_1 = Internal.createForeignKey(Keys.KEY_COLLEGE_PRIMARY, Course.COURSE, "course_ibfk_1", Course.COURSE.COLLEGE_ID);
        public static final ForeignKey<CurriculumContentRecord, CurriculumReleaseRecord> CURRICULUM_CONTENT_IBFK_1 = Internal.createForeignKey(Keys.KEY_CURRICULUM_RELEASE_PRIMARY, CurriculumContent.CURRICULUM_CONTENT, "curriculum_content_ibfk_1", CurriculumContent.CURRICULUM_CONTENT.CURRICULUM_RELEASE_ID);
        public static final ForeignKey<CurriculumContentRecord, UsersRecord> CURRICULUM_CONTENT_IBFK_2 = Internal.createForeignKey(Keys.KEY_USERS_PRIMARY, CurriculumContent.CURRICULUM_CONTENT, "curriculum_content_ibfk_2", CurriculumContent.CURRICULUM_CONTENT.PLAN_USERNAME);
        public static final ForeignKey<CurriculumReleaseRecord, CollegeRecord> CURRICULUM_RELEASE_IBFK_1 = Internal.createForeignKey(Keys.KEY_COLLEGE_PRIMARY, CurriculumRelease.CURRICULUM_RELEASE, "curriculum_release_ibfk_1", CurriculumRelease.CURRICULUM_RELEASE.COLLEGE_ID);
        public static final ForeignKey<CurriculumReleaseRecord, UsersRecord> CURRICULUM_RELEASE_IBFK_2 = Internal.createForeignKey(Keys.KEY_USERS_PRIMARY, CurriculumRelease.CURRICULUM_RELEASE, "curriculum_release_ibfk_2", CurriculumRelease.CURRICULUM_RELEASE.RELEASE_USERNAME);
        public static final ForeignKey<DepartmentRecord, CollegeRecord> DEPARTMENT_IBFK_1 = Internal.createForeignKey(Keys.KEY_COLLEGE_PRIMARY, Department.DEPARTMENT, "department_ibfk_1", Department.DEPARTMENT.COLLEGE_ID);
        public static final ForeignKey<GradeRecord, ScienceRecord> GRADE_IBFK_1 = Internal.createForeignKey(Keys.KEY_SCIENCE_PRIMARY, Grade.GRADE, "grade_ibfk_1", Grade.GRADE.SCIENCE_ID);
        public static final ForeignKey<OrganizeRecord, GradeRecord> ORGANIZE_IBFK_1 = Internal.createForeignKey(Keys.KEY_GRADE_PRIMARY, Organize.ORGANIZE, "organize_ibfk_1", Organize.ORGANIZE.GRADE_ID);
        public static final ForeignKey<RoleApplicationRecord, RoleRecord> ROLE_APPLICATION_IBFK_1 = Internal.createForeignKey(Keys.KEY_ROLE_PRIMARY, RoleApplication.ROLE_APPLICATION, "role_application_ibfk_1", RoleApplication.ROLE_APPLICATION.ROLE_ID);
        public static final ForeignKey<RoleApplicationRecord, ApplicationRecord> ROLE_APPLICATION_IBFK_2 = Internal.createForeignKey(Keys.KEY_APPLICATION_PRIMARY, RoleApplication.ROLE_APPLICATION, "role_application_ibfk_2", RoleApplication.ROLE_APPLICATION.APPLICATION_ID);
        public static final ForeignKey<SchoolroomRecord, BuildingRecord> SCHOOLROOM_IBFK_1 = Internal.createForeignKey(Keys.KEY_BUILDING_PRIMARY, Schoolroom.SCHOOLROOM, "schoolroom_ibfk_1", Schoolroom.SCHOOLROOM.BUILDING_ID);
        public static final ForeignKey<ScienceRecord, DepartmentRecord> SCIENCE_IBFK_1 = Internal.createForeignKey(Keys.KEY_DEPARTMENT_PRIMARY, Science.SCIENCE, "science_ibfk_1", Science.SCIENCE.DEPARTMENT_ID);
        public static final ForeignKey<StaffRecord, DepartmentRecord> STAFF_IBFK_1 = Internal.createForeignKey(Keys.KEY_DEPARTMENT_PRIMARY, Staff.STAFF, "staff_ibfk_1", Staff.STAFF.DEPARTMENT_ID);
        public static final ForeignKey<StaffRecord, UsersRecord> STAFF_IBFK_2 = Internal.createForeignKey(Keys.KEY_USERS_PRIMARY, Staff.STAFF, "staff_ibfk_2", Staff.STAFF.USERNAME);
        public static final ForeignKey<StudentRecord, OrganizeRecord> STUDENT_IBFK_1 = Internal.createForeignKey(Keys.KEY_ORGANIZE_PRIMARY, Student.STUDENT, "student_ibfk_1", Student.STUDENT.ORGANIZE_ID);
        public static final ForeignKey<StudentRecord, UsersRecord> STUDENT_IBFK_2 = Internal.createForeignKey(Keys.KEY_USERS_PRIMARY, Student.STUDENT, "student_ibfk_2", Student.STUDENT.USERNAME);
        public static final ForeignKey<SystemNotifyRecord, UsersRecord> SYSTEM_NOTIFY_IBFK_1 = Internal.createForeignKey(Keys.KEY_USERS_PRIMARY, SystemNotify.SYSTEM_NOTIFY, "system_notify_ibfk_1", SystemNotify.SYSTEM_NOTIFY.SEND_USER);
        public static final ForeignKey<TrainingAttendRecord, SchoolroomRecord> TRAINING_ATTEND_IBFK_1 = Internal.createForeignKey(Keys.KEY_SCHOOLROOM_PRIMARY, TrainingAttend.TRAINING_ATTEND, "training_attend_ibfk_1", TrainingAttend.TRAINING_ATTEND.ATTEND_ROOM);
        public static final ForeignKey<TrainingAttendRecord, TrainingReleaseRecord> TRAINING_ATTEND_IBFK_2 = Internal.createForeignKey(Keys.KEY_TRAINING_RELEASE_PRIMARY, TrainingAttend.TRAINING_ATTEND, "training_attend_ibfk_2", TrainingAttend.TRAINING_ATTEND.TRAINING_RELEASE_ID);
        public static final ForeignKey<TrainingAttendAuthoritiesRecord, TrainingAttendRecord> TRAINING_ATTEND_AUTHORITIES_IBFK_1 = Internal.createForeignKey(Keys.KEY_TRAINING_ATTEND_PRIMARY, TrainingAttendAuthorities.TRAINING_ATTEND_AUTHORITIES, "training_attend_authorities_ibfk_1", TrainingAttendAuthorities.TRAINING_ATTEND_AUTHORITIES.TRAINING_ATTEND_ID);
        public static final ForeignKey<TrainingAttendAuthoritiesRecord, UsersRecord> TRAINING_ATTEND_AUTHORITIES_IBFK_2 = Internal.createForeignKey(Keys.KEY_USERS_PRIMARY, TrainingAttendAuthorities.TRAINING_ATTEND_AUTHORITIES, "training_attend_authorities_ibfk_2", TrainingAttendAuthorities.TRAINING_ATTEND_AUTHORITIES.USERNAME);
        public static final ForeignKey<TrainingAttendLeaveApplyRecord, TrainingAttendRecord> TRAINING_ATTEND_LEAVE_APPLY_IBFK_1 = Internal.createForeignKey(Keys.KEY_TRAINING_ATTEND_PRIMARY, TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY, "training_attend_leave_apply_ibfk_1", TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY.TRAINING_ATTEND_ID);
        public static final ForeignKey<TrainingAttendLeaveApplyRecord, TrainingUsersRecord> TRAINING_ATTEND_LEAVE_APPLY_IBFK_2 = Internal.createForeignKey(Keys.KEY_TRAINING_USERS_PRIMARY, TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY, "training_attend_leave_apply_ibfk_2", TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY.TRAINING_USERS_ID);
        public static final ForeignKey<TrainingAttendUsersRecord, TrainingAttendRecord> TRAINING_ATTEND_USERS_IBFK_1 = Internal.createForeignKey(Keys.KEY_TRAINING_ATTEND_PRIMARY, TrainingAttendUsers.TRAINING_ATTEND_USERS, "training_attend_users_ibfk_1", TrainingAttendUsers.TRAINING_ATTEND_USERS.TRAINING_ATTEND_ID);
        public static final ForeignKey<TrainingAttendUsersRecord, TrainingUsersRecord> TRAINING_ATTEND_USERS_IBFK_2 = Internal.createForeignKey(Keys.KEY_TRAINING_USERS_PRIMARY, TrainingAttendUsers.TRAINING_ATTEND_USERS, "training_attend_users_ibfk_2", TrainingAttendUsers.TRAINING_ATTEND_USERS.TRAINING_USERS_ID);
        public static final ForeignKey<TrainingReleaseRecord, SchoolroomRecord> TRAINING_RELEASE_IBFK_1 = Internal.createForeignKey(Keys.KEY_SCHOOLROOM_PRIMARY, TrainingRelease.TRAINING_RELEASE, "training_release_ibfk_1", TrainingRelease.TRAINING_RELEASE.SCHOOLROOM_ID);
        public static final ForeignKey<TrainingReleaseRecord, UsersRecord> TRAINING_RELEASE_IBFK_2 = Internal.createForeignKey(Keys.KEY_USERS_PRIMARY, TrainingRelease.TRAINING_RELEASE, "training_release_ibfk_2", TrainingRelease.TRAINING_RELEASE.USERNAME);
        public static final ForeignKey<TrainingReleaseRecord, CourseRecord> TRAINING_RELEASE_IBFK_3 = Internal.createForeignKey(Keys.KEY_COURSE_PRIMARY, TrainingRelease.TRAINING_RELEASE, "training_release_ibfk_3", TrainingRelease.TRAINING_RELEASE.COURSE_ID);
        public static final ForeignKey<TrainingReleaseRecord, OrganizeRecord> TRAINING_RELEASE_IBFK_4 = Internal.createForeignKey(Keys.KEY_ORGANIZE_PRIMARY, TrainingRelease.TRAINING_RELEASE, "training_release_ibfk_4", TrainingRelease.TRAINING_RELEASE.ORGANIZE_ID);
        public static final ForeignKey<TrainingUsersRecord, TrainingReleaseRecord> TRAINING_USERS_IBFK_1 = Internal.createForeignKey(Keys.KEY_TRAINING_RELEASE_PRIMARY, TrainingUsers.TRAINING_USERS, "training_users_ibfk_1", TrainingUsers.TRAINING_USERS.TRAINING_RELEASE_ID);
        public static final ForeignKey<TrainingUsersRecord, StudentRecord> TRAINING_USERS_IBFK_2 = Internal.createForeignKey(Keys.KEY_STUDENT_PRIMARY, TrainingUsers.TRAINING_USERS, "training_users_ibfk_2", TrainingUsers.TRAINING_USERS.STUDENT_ID);
        public static final ForeignKey<UserNotifyRecord, UsersRecord> USER_NOTIFY_IBFK_1 = Internal.createForeignKey(Keys.KEY_USERS_PRIMARY, UserNotify.USER_NOTIFY, "user_notify_ibfk_1", UserNotify.USER_NOTIFY.SEND_USER);
        public static final ForeignKey<UserNotifyRecord, UsersRecord> USER_NOTIFY_IBFK_2 = Internal.createForeignKey(Keys.KEY_USERS_PRIMARY, UserNotify.USER_NOTIFY, "user_notify_ibfk_2", UserNotify.USER_NOTIFY.ACCEPT_USER);
        public static final ForeignKey<UsersRecord, UsersTypeRecord> USERS_IBFK_1 = Internal.createForeignKey(Keys.KEY_USERS_TYPE_PRIMARY, Users.USERS, "users_ibfk_1", Users.USERS.USERS_TYPE_ID);
        public static final ForeignKey<UsersRecord, FilesRecord> USERS_IBFK_2 = Internal.createForeignKey(Keys.KEY_FILES_PRIMARY, Users.USERS, "users_ibfk_2", Users.USERS.AVATAR);
    }
}
