/*
 * This file is generated by jOOQ.
 */
package top.zbeboy.zone.domain;


import javax.annotation.Generated;

import top.zbeboy.zone.domain.tables.AcademicTitle;
import top.zbeboy.zone.domain.tables.AchievementRelease;
import top.zbeboy.zone.domain.tables.AchievementSyncData;
import top.zbeboy.zone.domain.tables.AchievementSyncManifest;
import top.zbeboy.zone.domain.tables.AchievementSyncStudent;
import top.zbeboy.zone.domain.tables.Application;
import top.zbeboy.zone.domain.tables.Authorities;
import top.zbeboy.zone.domain.tables.Building;
import top.zbeboy.zone.domain.tables.College;
import top.zbeboy.zone.domain.tables.CollegeApplication;
import top.zbeboy.zone.domain.tables.CollegeRole;
import top.zbeboy.zone.domain.tables.Course;
import top.zbeboy.zone.domain.tables.CurriculumContent;
import top.zbeboy.zone.domain.tables.CurriculumRelease;
import top.zbeboy.zone.domain.tables.Department;
import top.zbeboy.zone.domain.tables.Files;
import top.zbeboy.zone.domain.tables.Grade;
import top.zbeboy.zone.domain.tables.Nation;
import top.zbeboy.zone.domain.tables.Organize;
import top.zbeboy.zone.domain.tables.PoliticalLandscape;
import top.zbeboy.zone.domain.tables.QuestionFeedback;
import top.zbeboy.zone.domain.tables.Role;
import top.zbeboy.zone.domain.tables.RoleApplication;
import top.zbeboy.zone.domain.tables.School;
import top.zbeboy.zone.domain.tables.Schoolroom;
import top.zbeboy.zone.domain.tables.Science;
import top.zbeboy.zone.domain.tables.Staff;
import top.zbeboy.zone.domain.tables.Student;
import top.zbeboy.zone.domain.tables.SystemConfigure;
import top.zbeboy.zone.domain.tables.SystemMailboxLog;
import top.zbeboy.zone.domain.tables.SystemNotify;
import top.zbeboy.zone.domain.tables.SystemOperatorLog;
import top.zbeboy.zone.domain.tables.SystemSmsLog;
import top.zbeboy.zone.domain.tables.TrainingAttend;
import top.zbeboy.zone.domain.tables.TrainingAttendAuthorities;
import top.zbeboy.zone.domain.tables.TrainingAttendLeaveApply;
import top.zbeboy.zone.domain.tables.TrainingAttendUsers;
import top.zbeboy.zone.domain.tables.TrainingLabs;
import top.zbeboy.zone.domain.tables.TrainingRelease;
import top.zbeboy.zone.domain.tables.TrainingUsers;
import top.zbeboy.zone.domain.tables.UserNotify;
import top.zbeboy.zone.domain.tables.Users;
import top.zbeboy.zone.domain.tables.UsersType;


/**
 * Convenience access to all tables in zhe
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>zhe.academic_title</code>.
     */
    public static final AcademicTitle ACADEMIC_TITLE = AcademicTitle.ACADEMIC_TITLE;

    /**
     * The table <code>zhe.achievement_release</code>.
     */
    public static final AchievementRelease ACHIEVEMENT_RELEASE = AchievementRelease.ACHIEVEMENT_RELEASE;

    /**
     * The table <code>zhe.achievement_sync_data</code>.
     */
    public static final AchievementSyncData ACHIEVEMENT_SYNC_DATA = AchievementSyncData.ACHIEVEMENT_SYNC_DATA;

    /**
     * The table <code>zhe.achievement_sync_manifest</code>.
     */
    public static final AchievementSyncManifest ACHIEVEMENT_SYNC_MANIFEST = AchievementSyncManifest.ACHIEVEMENT_SYNC_MANIFEST;

    /**
     * The table <code>zhe.achievement_sync_student</code>.
     */
    public static final AchievementSyncStudent ACHIEVEMENT_SYNC_STUDENT = AchievementSyncStudent.ACHIEVEMENT_SYNC_STUDENT;

    /**
     * The table <code>zhe.application</code>.
     */
    public static final Application APPLICATION = Application.APPLICATION;

    /**
     * The table <code>zhe.authorities</code>.
     */
    public static final Authorities AUTHORITIES = Authorities.AUTHORITIES;

    /**
     * The table <code>zhe.building</code>.
     */
    public static final Building BUILDING = Building.BUILDING;

    /**
     * The table <code>zhe.college</code>.
     */
    public static final College COLLEGE = College.COLLEGE;

    /**
     * The table <code>zhe.college_application</code>.
     */
    public static final CollegeApplication COLLEGE_APPLICATION = CollegeApplication.COLLEGE_APPLICATION;

    /**
     * The table <code>zhe.college_role</code>.
     */
    public static final CollegeRole COLLEGE_ROLE = CollegeRole.COLLEGE_ROLE;

    /**
     * The table <code>zhe.course</code>.
     */
    public static final Course COURSE = Course.COURSE;

    /**
     * The table <code>zhe.curriculum_content</code>.
     */
    public static final CurriculumContent CURRICULUM_CONTENT = CurriculumContent.CURRICULUM_CONTENT;

    /**
     * The table <code>zhe.curriculum_release</code>.
     */
    public static final CurriculumRelease CURRICULUM_RELEASE = CurriculumRelease.CURRICULUM_RELEASE;

    /**
     * The table <code>zhe.department</code>.
     */
    public static final Department DEPARTMENT = Department.DEPARTMENT;

    /**
     * The table <code>zhe.files</code>.
     */
    public static final Files FILES = Files.FILES;

    /**
     * The table <code>zhe.grade</code>.
     */
    public static final Grade GRADE = Grade.GRADE;

    /**
     * The table <code>zhe.nation</code>.
     */
    public static final Nation NATION = Nation.NATION;

    /**
     * The table <code>zhe.organize</code>.
     */
    public static final Organize ORGANIZE = Organize.ORGANIZE;

    /**
     * The table <code>zhe.political_landscape</code>.
     */
    public static final PoliticalLandscape POLITICAL_LANDSCAPE = PoliticalLandscape.POLITICAL_LANDSCAPE;

    /**
     * The table <code>zhe.question_feedback</code>.
     */
    public static final QuestionFeedback QUESTION_FEEDBACK = QuestionFeedback.QUESTION_FEEDBACK;

    /**
     * The table <code>zhe.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>zhe.role_application</code>.
     */
    public static final RoleApplication ROLE_APPLICATION = RoleApplication.ROLE_APPLICATION;

    /**
     * The table <code>zhe.school</code>.
     */
    public static final School SCHOOL = School.SCHOOL;

    /**
     * The table <code>zhe.schoolroom</code>.
     */
    public static final Schoolroom SCHOOLROOM = Schoolroom.SCHOOLROOM;

    /**
     * The table <code>zhe.science</code>.
     */
    public static final Science SCIENCE = Science.SCIENCE;

    /**
     * The table <code>zhe.staff</code>.
     */
    public static final Staff STAFF = Staff.STAFF;

    /**
     * The table <code>zhe.student</code>.
     */
    public static final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>zhe.system_configure</code>.
     */
    public static final SystemConfigure SYSTEM_CONFIGURE = SystemConfigure.SYSTEM_CONFIGURE;

    /**
     * The table <code>zhe.system_mailbox_log</code>.
     */
    public static final SystemMailboxLog SYSTEM_MAILBOX_LOG = SystemMailboxLog.SYSTEM_MAILBOX_LOG;

    /**
     * The table <code>zhe.system_notify</code>.
     */
    public static final SystemNotify SYSTEM_NOTIFY = SystemNotify.SYSTEM_NOTIFY;

    /**
     * The table <code>zhe.system_operator_log</code>.
     */
    public static final SystemOperatorLog SYSTEM_OPERATOR_LOG = SystemOperatorLog.SYSTEM_OPERATOR_LOG;

    /**
     * The table <code>zhe.system_sms_log</code>.
     */
    public static final SystemSmsLog SYSTEM_SMS_LOG = SystemSmsLog.SYSTEM_SMS_LOG;

    /**
     * The table <code>zhe.training_attend</code>.
     */
    public static final TrainingAttend TRAINING_ATTEND = TrainingAttend.TRAINING_ATTEND;

    /**
     * The table <code>zhe.training_attend_authorities</code>.
     */
    public static final TrainingAttendAuthorities TRAINING_ATTEND_AUTHORITIES = TrainingAttendAuthorities.TRAINING_ATTEND_AUTHORITIES;

    /**
     * The table <code>zhe.training_attend_leave_apply</code>.
     */
    public static final TrainingAttendLeaveApply TRAINING_ATTEND_LEAVE_APPLY = TrainingAttendLeaveApply.TRAINING_ATTEND_LEAVE_APPLY;

    /**
     * The table <code>zhe.training_attend_users</code>.
     */
    public static final TrainingAttendUsers TRAINING_ATTEND_USERS = TrainingAttendUsers.TRAINING_ATTEND_USERS;

    /**
     * The table <code>zhe.training_labs</code>.
     */
    public static final TrainingLabs TRAINING_LABS = TrainingLabs.TRAINING_LABS;

    /**
     * The table <code>zhe.training_release</code>.
     */
    public static final TrainingRelease TRAINING_RELEASE = TrainingRelease.TRAINING_RELEASE;

    /**
     * The table <code>zhe.training_users</code>.
     */
    public static final TrainingUsers TRAINING_USERS = TrainingUsers.TRAINING_USERS;

    /**
     * The table <code>zhe.user_notify</code>.
     */
    public static final UserNotify USER_NOTIFY = UserNotify.USER_NOTIFY;

    /**
     * The table <code>zhe.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>zhe.users_type</code>.
     */
    public static final UsersType USERS_TYPE = UsersType.USERS_TYPE;
}
